### ISSUE TITLE
Listing locals in block of var declarations panics

### ISSUE THREAD

**Issue by EVODelavega** [derekparker/delve#1075]
This issue is potentially related to #83 

While stepping through the `http.Client.Do()` call, I tried listing the local variables on line 498 (golang 1.8.3 docker image). I had just installed delve 1.0.0-rc.2 (full output of `{dlv,go} version` below). This resulted in a runtime panic (index out of range) probably when trying to pretty-print variables that hadn't been initialised at that point.

Going by the output it seems that the problem is that I was exactly on the line that declares `reqs        []*Request`. Variables later on that haven't been initialised do show up with an error message (for example `copyHeaders = (unreadable input/output error)`)

I'm not sure what the best course of action is, but I suspect there needs to be a nil check on slices like this, and display its value as `nil`, or even with the same error message as `copyHeaders` had. 

The relevant information below:

## Versions:

Delve:

```
dlv version
Delve Debugger
Version: 1.0.0-rc.2
Build: $Id: 5c7676404d10d52e16be57fea744a7312b831f0c $
```

Go

```
go version
go version go1.8.3 linux/amd64
```

OS/arch

docker image golang:1.8.3 (Debian jessie based):

```
# cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# uname -a
Linux 6adc032f03e8 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 GNU/Linux
```

## Delve trace

```
(dlv) s
> net/http.(*Client).Do() /usr/local/go/src/net/http/client.go:498 (PC: 0x5a3c18)
   493:			return nil, errors.New("http: nil Request.URL")
   494:		}
   495:	
   496:		var (
   497:			deadline    = c.deadline()
=> 498:			reqs        []*Request
   499:			resp        *Response
   500:			copyHeaders = c.makeHeadersCopier(req)
   501:	
   502:			// Redirect behavior:
   503:			redirectMethod string
(dlv) locals
includeBody = false
t·2.nsec = 0
t·2.sec = 0
redirectMethod.len = 842350530224
loc.len = 0
ue.itab = (*uint8)(0x8)
ue.data = (*uint8)(0x7fe083b2a000)
u = *net/url.URL nil
t·2.loc = *time.Location nil
redirectMethod.ptr = (*uint8)(0xc420043ae0)
loc.ptr = (*uint8)(0x40ff12)
ireq = (*net/http.Request)(0xc420060c60)
err.itab = (*uint8)(0x30)
err.itab#13 = (*uint8)(0x30)
err.data = (*uint8)(0x640040)
err.data#15 = (*uint8)(0x610bc0)
didTimeout = (unreadable input/output error)
copyHeaders = (unreadable input/output error)
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/derekparker/delve/service/api.(*Variable).writeTo(0xc4207e35c0, 0xc8ce00, 0xc4205558f0, 0xc420010001, 0x0, 0x0)
	/go/src/github.com/derekparker/delve/service/api/prettyprint.go:54 +0x10e9
github.com/derekparker/delve/service/api.(*Variable).SinglelineString(0xc4207e35c0, 0xc8cc80, 0x1)
	/go/src/github.com/derekparker/delve/service/api/prettyprint.go:20 +0x78
github.com/derekparker/delve/pkg/terminal.printFilteredVariables(0xa10e56, 0x6, 0xc420063500, 0x15, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x40, ...)
	/go/src/github.com/derekparker/delve/pkg/terminal/command.go:1021 +0x1bc
github.com/derekparker/delve/pkg/terminal.locals(0xc4204f2960, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x2, 0x6)
	/go/src/github.com/derekparker/delve/pkg/terminal/command.go:1096 +0x2c9
github.com/derekparker/delve/pkg/terminal.(*Commands).CallWithContext(0xc420572ed0, 0xc4204d5364, 0x6, 0xc4204f2960, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x6, 0xc4204d5364)
	/go/src/github.com/derekparker/delve/pkg/terminal/command.go:339 +0x134
github.com/derekparker/delve/pkg/terminal.(*Commands).Call(0xc420572ed0, 0xc4204d5364, 0x6, 0xc4204f2960, 0x0, 0x0)
	/go/src/github.com/derekparker/delve/pkg/terminal/command.go:344 +0x71
github.com/derekparker/delve/pkg/terminal.(*Term).Run(0xc4204f2960, 0x0, 0x0, 0x0)
	/go/src/github.com/derekparker/delve/pkg/terminal/terminal.go:132 +0x38f
github.com/derekparker/delve/cmd/dlv/cmds.execute(0x0, 0xc42011c8b0, 0x1, 0x1, 0xc42011e2c0, 0x0, 0x0, 0x1, 0x0)
	/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:537 +0x94f
github.com/derekparker/delve/cmd/dlv/cmds.debugCmd.func1(0xc420142900, 0xc42011c670, 0x1, 0x1, 0x0)
	/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:300 +0x41d
github.com/derekparker/delve/cmd/dlv/cmds.debugCmd(0xc420142900, 0xc42011c670, 0x1, 0x1)
	/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:301 +0x49
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc420142900, 0xc42011c610, 0x1, 0x1, 0xc420142900, 0xc42011c610)
	/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:647 +0x234
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420142240, 0xc420142b40, 0xc420142900, 0xc4201426c0)
	/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:733 +0x339
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420142240, 0xc420142240, 0xa0eedf)
	/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:692 +0x2b
main.main()
	/go/src/github.com/derekparker/delve/cmd/dlv/main.go:18 +0x91
```

**Comment by EVODelavega** [comment]
I just noticed there was a core dump file in the directory. I ran `dlv core` using the commands below, not sure what to make of that additional info, but thought it best to add it here, too.

I ran delve with `dlv debug main.go`, so I compiled the source file (simple `go build main.go`), and loaded up the core dump:

```
# dlv core ./main core.1104 
Type 'help' for list of commands.
(dlv) bt
0  0x0000000000429fd1 in runtime.startpanic
   at /usr/local/go/src/runtime/panic.go:568
1  0x0000000000000000 in (nil)
   at :0
   error: NULL address
(dlv) ls
> runtime.startpanic() /usr/local/go/src/runtime/panic.go:568 (PC: 0x429fd1)
   563:		}
   564:		return nil
   565:	}
   566:	
   567:	//go:nosplit
=> 568:	func startpanic() {
   569:		systemstack(startpanic_m)
   570:	}
   571:	
   572:	//go:nosplit
   573:	func dopanic(unused int) {
(dlv) stepout
   563:		}
   564:		return nil
   565:	}
   566:	
   567:	//go:nosplit
=> 568:	func startpanic() {
   569:		systemstack(startpanic_m)
   570:	}
   571:	
   572:	//go:nosplit
   573:	func dopanic(unused int) {
Command failed: Internal debugger error: runtime error: invalid memory address or nil pointer dereference
runtime.call32 (0x4543a8)
	/usr/local/go/src/runtime/asm_amd64.s:514
runtime.gopanic (0x42a0ff)
	/usr/local/go/src/runtime/panic.go:489
runtime.panicmem (0x428fae)
	/usr/local/go/src/runtime/panic.go:63
runtime.sigpanic (0x43f46f)
	/usr/local/go/src/runtime/signal_unix.go:290
github.com/derekparker/delve/pkg/proc.FirstPCAfterPrologue (0x66dfe5)
	/go/src/github.com/derekparker/delve/pkg/proc/disasm_amd64.go:147
github.com/derekparker/delve/pkg/proc.StepOut (0x67eebf)
	/go/src/github.com/derekparker/delve/pkg/proc/proc.go:297
github.com/derekparker/delve/service/debugger.(*Debugger).Command (0x714d88)
	/go/src/github.com/derekparker/delve/service/debugger/debugger.go:514
github.com/derekparker/delve/service/rpc2.(*RPCServer).Command (0x8b32f1)
	/go/src/github.com/derekparker/delve/service/rpc2/server.go:104
runtime.call64 (0x454428)
	/usr/local/go/src/runtime/asm_amd64.s:515
reflect.Value.call (0x4a298f)
	/usr/local/go/src/reflect/value.go:434
reflect.Value.Call (0x4a1f54)
	/usr/local/go/src/reflect/value.go:302
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func2 (0x8bc562)
	/go/src/github.com/derekparker/delve/service/rpccommon/server.go:318
runtime.goexit (0x456b41)
	/usr/local/go/src/runtime/asm_amd64.s:2197

(dlv) q
```

restart/rewind/step and all that didn't work (`Command failed: can not continue execution of core process`)

**Comment by dlsniper** [comment]
I would say first upgrade to at least Go 1.9.2 and try again. Go itself gained a lot more information for the debuggers to use and this would help out investigating against the current Go version. Also, Go 1.10 beta1 further improves the debugging information quality but that might not be something you can use.

**Comment by EVODelavega** [comment]
@dlsniper OK, so I ran the same code on the golang:1.9.2 container, and it seems everything works fine then. Might be worth a look considering 1.8 is still quite common, and for the debugger to crash like that when stepping through a standard library package (`net/http`) is rather unexpected.

Anyway, the output on 1.9.2, same breakpoint, same `locals` command:

```
> net/http.(*Client).Do() /usr/local/go/src/net/http/client.go:498 (hits goroutine(1):1 total:1) (PC: 0x5c5e8e)
Warning: debugging optimized function
   493:			return nil, errors.New("http: nil Request.URL")
   494:		}
   495:	
   496:		var (
   497:			deadline      = c.deadline()
=> 498:			reqs          []*Request
   499:			resp          *Response
   500:			copyHeaders   = c.makeHeadersCopier(req)
   501:			reqBodyClosed = false // have we closed the current req.Body?
   502:	
   503:			// Redirect behavior:
(dlv) locals
includeBody = false
redirectMethod.len = 842350580592
loc.len = 842350580480
deadline.wall = 0
deadline.ext = 0
ue.itab = (*uint8)(0xc420109a40)
ue.data = (*uint8)(0x42a6a6)
u = (*net/url.URL)(0x6a3338)
redirectMethod.ptr = (*uint8)(0xc420109a50)
loc.ptr = *uint8 nil
ireq = (*net/http.Request)(0xc420000180)
err.itab = (*uint8)(0xc420109ac8)
err.itab = (*uint8)(0x411ad7)
err.data = (*uint8)(0xc4200f8100)
err.data = (*uint8)(0x80)
didTimeout = (unreadable input/output error)
deadline.loc = *time.Location nil
copyHeaders = (unreadable could not find function for 0x0)
resp = *(unreadable input/output error)
reqs = []*net/http.Request len: 6177195, cap: 6810976, [...]
reqBodyClosed = true
req = (*net/http.Request)(0xc4200fa200)
t·2 = time.Time {wall: 6177195, ext: 6810976, loc: (*time.Location)(0xc4200f8100)}
(dlv) 
```

**Comment by dlsniper** [comment]
I've sent #1076 to address this
