### ISSUE TITLE
Panic on 'next' with 'dlv test' on Linux AMD64

### ISSUE THREAD

**Issue by nuss-justin** [derekparker/delve#137]
Delve version: 0.5.0.beta (8f4f54d22ab6fcf0f97660575b9164fe51ab3fac)
go version go1.4.2 linux/amd64

I just tried delve and got a panic when I tried to use 'n' in my code. My code can be found here https://github.com/nuss-justin/keyvalue.

I used the following commands:

![bildschirmfoto vom 2015-05-24 19-11-52](https://cloud.githubusercontent.com/assets/6443781/7788750/cbb088f6-0248-11e5-9e1a-236c7e05e341.png)

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: interface conversion: interface is runtime.errorString, not source.Done
[signal 0xb code=0x1 addr=0x28 pc=0x667e4d]

goroutine 9 [running]:
github.com/derekparker/delve/source.func·002()
	/home/nussjustin/.go/src/github.com/derekparker/delve/source/source.go:68 +0x7a
github.com/derekparker/delve/source.(*Searcher).NextLines(0xc2080289b0, 0xc2082f2e60, 0x4e, 0xaf, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/source/source.go:123 +0xa6d
github.com/derekparker/delve/proctl.(*ThreadContext).next(0xc208290d80, 0x4616ee, 0xc2081735c0, 0xc2082f2e60, 0x4e, 0xaf, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/proctl/threads.go:183 +0x7d
github.com/derekparker/delve/proctl.(*ThreadContext).Next(0xc208290d80, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/proctl/threads.go:160 +0x1b1
github.com/derekparker/delve/proctl.(*DebuggedProcess).next(0xc2080ca0c0, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/proctl/proctl.go:269 +0x3f6
github.com/derekparker/delve/proctl.*DebuggedProcess.(github.com/derekparker/delve/proctl.next)·fm(0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/proctl/proctl.go:235 +0x39
github.com/derekparker/delve/proctl.(*DebuggedProcess).run(0xc2080ca0c0, 0xc20847fbd8, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/proctl/proctl.go:609 +0x1b1
github.com/derekparker/delve/proctl.(*DebuggedProcess).Next(0xc2080ca0c0, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/proctl/proctl.go:235 +0x77
github.com/derekparker/delve/service/debugger.func·009(0xc2080ca0c0, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/debugger/debugger.go:304 +0xfd
github.com/derekparker/delve/service/debugger.func·001(0xc2080ca0c0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/debugger/debugger.go:73 +0x38
github.com/derekparker/delve/service/debugger.(*Debugger).Run(0xc20803b2f0, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/debugger/debugger.go:112 +0x55f
github.com/derekparker/delve/service/rest.func·001()
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/rest/server.go:68 +0x3b
created by github.com/derekparker/delve/service/rest.(*RESTServer).Run
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/rest/server.go:73 +0x26f

goroutine 1 [select]:
net/http.(*persistConn).roundTrip(0xc208030790, 0xc208283a20, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc208060000, 0xc20801fd40, 0xc2082ca7c0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:235 +0x558
net/http.send(0xc20801fd40, 0x7f687f381ef0, 0xc208060000, 0x1e, 0x0, 0x0)
	/usr/lib/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc20803b110, 0xc20801fd40, 0x1e, 0x0, 0x0)
	/usr/lib/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc20803b110, 0xc20801fd40, 0x9412c8, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xc20803b110, 0xc20801fd40, 0xc, 0x0, 0x0)
	/usr/lib/go/src/net/http/client.go:177 +0x192
github.com/derekparker/delve/service/rest.(*RESTClient).doPOST(0xc20800aa60, 0x87fdb0, 0x8, 0x714540, 0xc2082ca780, 0x70ae20, 0xc20802a3c0, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/rest/client.go:321 +0x2ac
github.com/derekparker/delve/service/rest.(*RESTClient).Next(0xc20800aa60, 0x2, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/rest/client.go:72 +0xdb
github.com/derekparker/delve/terminal.next(0x7f687f383248, 0xc20800aa60, 0xc2082839c0, 0x0, 0x0, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/terminal/command.go:213 +0x43
github.com/derekparker/delve/terminal.(*Term).Run(0xc20803b1a0, 0x0, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/terminal/terminal.go:93 +0x9e1
main.main()
	/home/nussjustin/.go/src/github.com/derekparker/delve/cmd/dlv/main.go:126 +0xa77

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [IO wait]:
net.(*pollDesc).Wait(0xc208010290, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010290, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010230, 0x0, 0x7f687f381c18, 0xc208282868)
	/usr/lib/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802a050, 0xc208083bf8, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20802a050, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc20802ed20, 0x7f687f3821d8, 0xc20802a050, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f687f3821d8, 0xc20802a050, 0x7f687f384440, 0xc2080102a0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1606 +0xa1
github.com/derekparker/delve/service/rest.(*RESTServer).Run(0xc20803b0e0, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/rest/server.go:106 +0x1557
created by main.main
	/home/nussjustin/.go/src/github.com/derekparker/delve/cmd/dlv/main.go:119 +0x887

goroutine 7 [chan receive]:
github.com/derekparker/delve/terminal.func·002()
	/home/nussjustin/.go/src/github.com/derekparker/delve/terminal/terminal.go:48 +0x6d
created by github.com/derekparker/delve/terminal.(*Term).Run
	/home/nussjustin/.go/src/github.com/derekparker/delve/terminal/terminal.go:54 +0x2cb

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc2080106f0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080106f0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010690, 0xc20829a000, 0x1000, 0x1000, 0x0, 0x7f687f381c18, 0xc208283950)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802a0d0, 0xc20829a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f687f389ab8, 0xc20802a0d0, 0xc2080307e8, 0xc20829a000, 0x1000, 0x1000, 0x7972e0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208296420, 0xc20829a000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20802fb60)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20802fb60, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208030790)
	/usr/lib/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:660 +0xc9f

goroutine 15 [chan receive]:
github.com/derekparker/delve/service/debugger.(*Debugger).withProcess(0xc20803b2f0, 0x941048, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/debugger/debugger.go:75 +0x1dc
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc20803b2f0, 0xc2082ca940, 0xc2082ca940, 0x0, 0x0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/debugger/debugger.go:305 +0x385
github.com/derekparker/delve/service/rest.(*RESTServer).doCommand(0xc20803b0e0, 0xc2082c6c00, 0xc20802ddb0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/rest/server.go:159 +0xda
github.com/derekparker/delve/service/rest.*RESTServer.(github.com/derekparker/delve/service/rest.doCommand)·fm(0xc2082c6c00, 0xc20802ddb0)
	/home/nussjustin/.go/src/github.com/derekparker/delve/service/rest/server.go:93 +0x3b
github.com/emicklei/go-restful.(*Container).dispatch(0xc2080102a0, 0x7f687f389e78, 0xc20807b680, 0xc20801fc70)
	/home/nussjustin/.go/src/github.com/emicklei/go-restful/container.go:220 +0xf4a
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f687f389e78, 0xc20807b680, 0xc20801fc70)
	/home/nussjustin/.go/src/github.com/emicklei/go-restful/container.go:91 +0x45
net/http.HandlerFunc.ServeHTTP(0xc2080bde90, 0x7f687f389e78, 0xc20807b680, 0xc20801fc70)
	/usr/lib/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20803b350, 0x7f687f389e78, 0xc20807b680, 0xc20801fc70)
	/usr/lib/go/src/net/http/server.go:1541 +0x17d
github.com/emicklei/go-restful.Container.ServeHTTP(0xc20802a0d8, 0x1, 0x1, 0xc20803b350, 0x1, 0xc960b8, 0x0, 0x0, 0x0, 0x9410d0, ...)
	/home/nussjustin/.go/src/github.com/emicklei/go-restful/container.go:235 +0x4f
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc2080102a0, 0x7f687f389e78, 0xc20807b680, 0xc20801fc70)
	<autogenerated>:23 +0xdb
net/http.serverHandler.ServeHTTP(0xc20802ed20, 0x7f687f389e78, 0xc20807b680, 0xc20801fc70)
	/usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20807a820)
	/usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:1751 +0x35e

goroutine 18 [select]:
net/http.(*persistConn).writeLoop(0xc208030790)
	/usr/lib/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:661 +0xcbc
SIGTRAP: trace trap
PC=0x4616ee

goroutine 6 [running]:
_/home/nussjustin/Workspace/src/github.com/nuss-justin/keyvalue.TestEncoder(0xc208060090)
	/home/nussjustin/Workspace/src/github.com/nuss-justin/keyvalue/encoder_test.go:175 +0x1ee fp=0xc20802bf78 sp=0xc20802bca0
testing.tRunner(0xc208060090, 0x617db8)
	/usr/lib/go/src/testing/testing.go:447 +0xbf fp=0xc20802bfd0 sp=0xc20802bf78
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20802bfd8 sp=0xc20802bfd0
created by testing.RunTests
	/usr/lib/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x5a0970, 0x617da0, 0x3, 0x3, 0x7f4ad793f001)
	/usr/lib/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208056140, 0x617da0)
	/usr/lib/go/src/testing/testing.go:485 +0x6c
main.main()
	_/home/nussjustin/Workspace/src/github.com/nuss-justin/keyvalue/_test/_testmain.go:62 +0xb8

rax     0x1c
rbx     0x0
rcx     0x1c
rdx     0xc208038510
rdi     0xc208010104
rsi     0xc208038510
rbp     0xc2080100e0
rsp     0xc20802bca0
r8      0x99ac5
r9      0x30
r10     0x30
r11     0x0
r12     0xc20805e050
r13     0x0
r14     0x2
r15     0xc208038480
rip     0x4616ee
rflags  0x10202
cs      0x33
fs      0x0
gs      0x0
```

**Comment by dullgiulio** [comment]
In source/source.go 65, what is the "e = e.(Done)" for? I think that should be removed as it's unused.

**Comment by derekparker** [comment]
@dullgiulio basically that check ensures that the only reason we've gotten to that recover is because we were actually finished, not because of a legitimate runtime error.

There's weird flow of control stuff happening in that file to ensure we can stop traversing the tree as soon as we're done, as opposed to continuing parsing the rest of the file.

The actual error seems to have come from not checking that `x.Else` was non-nil before using it. I've closed the issue because I think the commit I just pushed should fix it. Could you verify, and if it is still panic'ing I will reopen.
