### ISSUE TITLE
Negative line numbers and broken breakpoints if using Go's `println` builtin, occasional panic

### ISSUE THREAD

**Issue by dominikh** [derekparker/delve#150]
# Code
```
package main

func main() {
	println(1)
	println(2)
}
```

# Session
```
dominikh-pc /tmp/meow2 $ dlv run
Type 'help' for list of commands.
(dlv) break meow.go:4
Breakpoint 1 set at 0x400c1a for main.main /tmp/meow2/meow.go:4
(dlv) break meow.go:5
Breakpoint 2 set at 0x400c2c for main.main /tmp/meow2/meow.go:5
(dlv) continue
current loc: main.main /tmp/meow2/meow.go:4
   -1: package main
   0: 
   1: func main() {
   2: 	println(1)
   3: 	println(2)
=> 4: }

(dlv) continue
1
2
Command failed: no such process
(dlv) 
```

Sometimes, when using `dlv <binary>` on an optimized binary, this even triggers a panic, although it took me several attempts to trigger it:

```
dominikh-pc /tmp/meow2 $ go build meow.go
dominikh-pc /tmp/meow2 $ dlv ./meow
Type 'help' for list of commands.
(dlv) break meow.go:4
Breakpoint 1 set at 0x400c1a for main.main /tmp/meow2/meow.go:4
(dlv) break meow.go:5
Breakpoint 2 set at 0x400c2c for main.main /tmp/meow2/meow.go:5
(dlv) continue
current loc: main.main /tmp/meow2/meow.go:4
   -1: package main
   0: 
   1: func main() {
   2: 	println(1)
   3: 	println(2)
=> 4: }

(dlv) continue
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5e9a03]

goroutine 25 [running]:
github.com/derekparker/delve/proc.func·015()
	/home/dominikh/prj/go/src/github.com/derekparker/delve/proc/threads.go:86 +0xa3
github.com/derekparker/delve/proc.(*Thread).Step(0xc208188300, 0x7fac55718c28, 0xc20818e9f0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/proc/threads.go:94 +0x3b4
github.com/derekparker/delve/proc.(*Thread).Continue(0xc208188300, 0x0, 0x0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/proc/threads.go:53 +0xb2
github.com/derekparker/delve/proc.(*Process).Continue(0xc2080309a0, 0x0, 0x0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/proc/proc.go:363 +0x9d
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc208028da0, 0xc20818b120, 0x7fac55710790, 0x0, 0x0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/service/debugger/debugger.go:167 +0x1d3
github.com/derekparker/delve/service/rpc.(*RPCServer).Command(0xc2080d01a0, 0xc20818b120, 0xc20818b140, 0x0, 0x0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/service/rpc/server.go:81 +0x48
reflect.Value.call(0x8511e0, 0x90f970, 0x13, 0x92bd50, 0x4, 0xc20819ff28, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/lib/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x8511e0, 0x90f970, 0x13, 0xc20819ff28, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/lib/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc2080841c0, 0xc208084180, 0xc208029e90, 0xc2080d4300, 0xc208190440, 0x798d00, 0xc20818b120, 0x16, 0x798d60, 0xc20818b140, ...)
	/usr/lib/go/src/net/rpc/server.go:382 +0x1f7
created by net/rpc.(*Server).ServeCodec
	/usr/lib/go/src/net/rpc/server.go:476 +0x44a

goroutine 1 [chan receive]:
net/rpc.(*Client).Call(0xc2081040c0, 0xc208190ce0, 0x11, 0x798d00, 0xc208190cc0, 0x798d60, 0xc208190ca0, 0x0, 0x0)
	/usr/lib/go/src/net/rpc/client.go:315 +0xd6
github.com/derekparker/delve/service/rpc.(*RPCClient).call(0xc2080d0240, 0x92c3b0, 0x7, 0x798d00, 0xc208190cc0, 0x798d60, 0xc208190ca0, 0x0, 0x0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/service/rpc/client.go:185 +0xb1
github.com/derekparker/delve/service/rpc.(*RPCClient).Continue(0xc2080d0240, 0x2, 0x0, 0x0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/service/rpc/client.go:46 +0xdb
github.com/derekparker/delve/terminal.cont(0x7fac5571f728, 0xc2080d0240, 0xc20818e9a0, 0x0, 0x0, 0x0, 0x0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/terminal/command.go:199 +0x40
github.com/derekparker/delve/terminal.(*Term).Run(0xc2080ca7e0, 0x0, 0x0, 0x0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/terminal/terminal.go:92 +0x9d2
main.run(0x96dfb0, 0xb, 0x0, 0x0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/cmd/dlv/main.go:155 +0x764
main.main()
	/home/dominikh/prj/go/src/github.com/derekparker/delve/cmd/dlv/main.go:67 +0x3fa

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc2080309a0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/proc/proc.go:666 +0x5d
created by github.com/derekparker/delve/proc.New
	/home/dominikh/prj/go/src/github.com/derekparker/delve/proc/proc.go:72 +0x215

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 18 [IO wait]:
net.(*pollDesc).Wait(0xc208010b50, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010b50, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010af0, 0xc20819a001, 0x5ff, 0x5ff, 0x0, 0x7fac55718c00, 0xc2080cd880)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802a078, 0xc20819a001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
encoding/json.(*Decoder).readValue(0xc208118180, 0x415910, 0x0, 0x0)
	/usr/lib/go/src/encoding/json/stream.go:124 +0x5e1
encoding/json.(*Decoder).Decode(0xc208118180, 0x86e120, 0xc208104320, 0x0, 0x0)
	/usr/lib/go/src/encoding/json/stream.go:44 +0x7b
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc208104300, 0xc20818a1e0, 0x0, 0x0)
	/usr/lib/go/src/net/rpc/jsonrpc/server.go:66 +0x9c
net/rpc.(*Server).readRequestHeader(0xc208084180, 0x7fac5571fad8, 0xc208104300, 0x0, 0x0, 0xc20818a1e0, 0x40f900, 0x0, 0x0)
	/usr/lib/go/src/net/rpc/server.go:575 +0x97
net/rpc.(*Server).readRequest(0xc208084180, 0x7fac5571fad8, 0xc208104300, 0xc2080d4300, 0xc208190440, 0x798d00, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/net/rpc/server.go:542 +0xa2
net/rpc.(*Server).ServeCodec(0xc208084180, 0x7fac5571fad8, 0xc208104300)
	/usr/lib/go/src/net/rpc/server.go:461 +0x6d
github.com/derekparker/delve/service/rpc.(*RPCServer).Run(0xc2080d01a0, 0x0, 0x0)
	/home/dominikh/prj/go/src/github.com/derekparker/delve/service/rpc/server.go:63 +0x2b0
created by main.run
	/home/dominikh/prj/go/src/github.com/derekparker/delve/cmd/dlv/main.go:143 +0x5b7

goroutine 19 [IO wait]:
net.(*pollDesc).Wait(0xc208102140, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208102140, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2081020e0, 0xc2081a6001, 0x5ff, 0x5ff, 0x0, 0x7fac55718c00, 0xc20818e968)
	/usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080d2030, 0xc2081a6001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:121 +0xdc
encoding/json.(*Decoder).readValue(0xc208118000, 0xc208190820, 0x0, 0x0)
	/usr/lib/go/src/encoding/json/stream.go:124 +0x5e1
encoding/json.(*Decoder).Decode(0xc208118000, 0x86e060, 0xc2080d4148, 0x0, 0x0)
	/usr/lib/go/src/encoding/json/stream.go:44 +0x7b
net/rpc/jsonrpc.(*clientCodec).ReadResponseHeader(0xc2080d4100, 0xc20803bcb0, 0x0, 0x0)
	/usr/lib/go/src/net/rpc/jsonrpc/client.go:75 +0xaf
net/rpc.(*Client).input(0xc2081040c0)
	/usr/lib/go/src/net/rpc/client.go:109 +0xb6
created by net/rpc.NewClientWithCodec
	/usr/lib/go/src/net/rpc/client.go:201 +0xd0

goroutine 20 [chan receive]:
github.com/derekparker/delve/terminal.func·002()
	/home/dominikh/prj/go/src/github.com/derekparker/delve/terminal/terminal.go:47 +0x6d
created by github.com/derekparker/delve/terminal.(*Term).Run
	/home/dominikh/prj/go/src/github.com/derekparker/delve/terminal/terminal.go:53 +0x2c2
SIGTRAP: trace trap%                                                                                                                                                 
```

# System
```
dominikh-pc ~ $ go version; dlv --version; (cd ~/prj/go/src/github.com/derekparker/delve; git rev-parse HEAD); uname -a
go version go1.4.2 linux/amd64
Delve version: 0.5.0.beta
dc00ff5832c3feda3ee27c33aacf829a2619c8fc
Linux dominikh-pc 3.18.7_1 #1 SMP PREEMPT Wed Feb 11 08:54:40 UTC 2015 x86_64 GNU/Linux
```

**Comment by aarzilli** [comment]
This doesn't happen when using go1.5 or go1.6. It sounds like it might have been a bug with go1.4 compiler.
