### ISSUE TITLE
`info locals` crashes with "len out of range" error

### ISSUE THREAD

**Issue by joeshaw** [derekparker/delve#189]
Running Delve 0.6.0.beta (a506bb7) and go version go1.4.2 darwin/amd64.  I was trying to reproduce this with a simpler program when I ran into #186, but haven't had success so far.  A fairly complicated program crashes when I run `info local` in the `main.main` function:

```
$ dlv run
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0xaa85 for main.main /Users/joeshaw/src/gosrc/src/<redacted>/main.go:643
(dlv) c
> main.main() /Users/joeshaw/src/gosrc/src/<redacted>/main.go:643

   638:		}
   639:	}
   640:
   641:	func main() {
   642:		// Override cli's hardcoded versioning
=> 643:		var showVersion bool
   644:		flag.BoolVar(&showVersion, "v", showVersion, "")
   645:		flag.BoolVar(&showVersion, "version", showVersion, "")
   646:		flag.Parse()
   647:
   648:		if showVersion {

(dlv) info locals
panic: runtime error: makeslice: len out of range

goroutine 21 [running]:
github.com/derekparker/delve/proc.(*Thread).readMemory(0xc2089fe060, 0x536567617373656d, 0x637365447465, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/proc/variables.go:794 +0xb6
github.com/derekparker/delve/proc.(*Thread).readString(0xc2089fe060, 0x536567617373656d, 0x0, 0x0, 0x0, 0x0)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/proc/variables.go:580 +0x4d7
github.com/derekparker/delve/proc.(*Thread).extractValueInternal(0xc2089fe060, 0x0, 0x0, 0x0, 0x7e9290, 0x4492060, 0xc208dabd40, 0x41d5b01, 0x1, 0x0, ...)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/proc/variables.go:509 +0x70a
github.com/derekparker/delve/proc.(*Thread).extractValueInternal(0xc2089fe060, 0x0, 0x0, 0x0, 0x7e9270, 0x4492060, 0xc208daa480, 0x1, 0x0, 0x0, ...)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/proc/variables.go:518 +0x9a7
github.com/derekparker/delve/proc.(*Thread).extractValueInternal(0xc2089fe060, 0xc208396b7d, 0x5, 0x20d561, 0xc20811bea0, 0x447ce40, 0xc208339890, 0x1, 0x0, 0x0, ...)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/proc/variables.go:500 +0x1623
github.com/derekparker/delve/proc.(*Thread).extractValue(0xc2089fe060, 0xc208396b7d, 0x5, 0x20d561, 0x0, 0x447ce40, 0xc208339890, 0xc208083601, 0x0, 0x0, ...)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/proc/variables.go:463 +0xb8
github.com/derekparker/delve/proc.(*Thread).extractVariableFromEntry(0xc2089fe060, 0xc208277d10, 0x0, 0x0, 0x0)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/proc/variables.go:396 +0x55f
github.com/derekparker/delve/proc.(*Thread).variablesByTag(0xc2089fe060, 0x57d563b300000034, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/proc/variables.go:824 +0x238
github.com/derekparker/delve/proc.(*Thread).LocalVariables(0xc2089fe060, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/proc/variables.go:248 +0x5d
github.com/derekparker/delve/service/debugger.(*Debugger).LocalVariables(0xc208029160, 0x2403, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/service/debugger/debugger.go:354 +0x220
github.com/derekparker/delve/service/rpc.(*RPCServer).ListLocalVars(0xc20800b520, 0x0, 0x0, 0xc20826bd80, 0x0, 0x0)
	/Users/joeshaw/src/gosrc/src/github.com/derekparker/delve/service/rpc/server.go:224 +0x96
reflect.Value.call(0x4414b00, 0x44d0930, 0x13, 0x44eb0e0, 0x4, 0xc20900ff28, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x4414b00, 0x44d0930, 0x13, 0xc20900ff28, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc208278880, 0xc208278840, 0xc20833ccd8, 0xc2080bc980, 0xc20831a8e0, 0x4383a00, 0xc2082ddf50, 0xd4, 0x4360780, 0xc20826bd80, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/rpc/server.go:382 +0x1f7
created by net/rpc.(*Server).ServeCodec
	/usr/local/Cellar/go/1.4.2/libexec/src/net/rpc/server.go:476 +0x44a
```

**Comment by joeshaw** [comment]
By the way, this seems to happen no matter where I try to run `info locals` in `main.main` -- doesn't have to be at the first line.

**Comment by bitshark** [comment]
Related issue here, possibly identical .  Version & path info & code included. #189
