### ISSUE TITLE
info locals causes panic: runtime error: makeslice: len out of range #171 #189 Related 

### ISSUE THREAD

**Issue by bitshark** [derekparker/delve#227]
related to issue: info locals causes panic: runtime error: makeslice: len out of range #171

``` shell
user@computer:~/bitshark/testgdb$ uname -a |fold -w 80            
Linux computer 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 
2015 x86_64 x86_64 x86_64 GNU/Linux

user@computer:~/bitshark/testgdb$ env | grep -i go | fold -w 80
PATH=/tank/home/user/.rbenv/plugins/ruby-build/bin:/tank/home/user/.rbenv/shims:
/tank/home/user/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sb
in:/bin:/usr/games:/usr/local/games:/opt/go/bin:/tank/home/user/go/bin:/sbin:/bi
n:/opt/android-studio/bin:/opt/android-studio/lib:/opt/android-studio/plugins
GOROOT=/opt/go
GOPATH=/tank/home/user/gocode
user@computer:~/bitshark/testgdb$ 

user@computer:~/bitshark/testgdb$ go version
go version go1.4.2 linux/amd64

user@computer:~/bitshark/testgdb$ dlv version
Delve version: 0.8.1-alpha
user@computer:~/bitshark/testgdb$ dlv ^C  
user@computer:~/bitshark/testgdb$ cat testgdb.go 
package main

import "fmt"

type MyStruct struct {
    x string
    i int
    f float64
}

func main() {
    x := "abc"
    i := 3
    fmt.Println(i)
    fmt.Println(x)

    ms := &MyStruct{
        x: "cba",
        i: 10,
        f: 11.10335,
    }
    fmt.Println(ms)
}


user@computer:~/bitshark/testgdb$ dlv debug testgdb.go 
Type 'help' for list of commands.

(dlv) break main.main
Breakpoint 1 set at 0x400c25 for main.main ./testgdb.go:12
(dlv) restart
Process restarted with PID 8097
(dlv) c
> main.main() ./testgdb.go:12

    7:      i int
    8:      f float64
    9:  }
   10:  
   11:  func main() {
=> 12:      x := "abc"
   13:      i := 3
   14:      fmt.Println(i)
   15:      fmt.Println(x)
   16:  
   17:      ms := &MyStruct{

(dlv) info locals
Command failed: command not available
(dlv) locals
panic: runtime error: makeslice: len out of range

goroutine 31 [running]:
github.com/derekparker/delve/proc.(*Thread).readMemory(0xc208248a20, 0x1, 
0x88010100663e425f, 0x0, 0x0, 0x0, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/threads_linux.go:84
 +0x12f
github.com/derekparker/delve/proc.(*Thread).readString(0xc208248a20, 0x1, 0x0, 
0x0, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/variables.go:588 
+0x4e9
github.com/derekparker/delve/proc.(*EvalScope).extractValueInternal(0xc208405380
, 0x0, 0x0, 0x0, 0x49f6e0, 0x906d60, 0xc20832a360, 0xc208010c01, 0x1, 0x0, ...)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/variables.go:515 
+0x7da
github.com/derekparker/delve/proc.(*EvalScope).extractValueInternal(0xc208405380
, 0x0, 0x0, 0x0, 0x49f6e0, 0x906d60, 0xc20839bc80, 0x1, 0x0, 0x0, ...)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/variables.go:524 
+0xa84
github.com/derekparker/delve/proc.(*EvalScope).extractValueInternal(0xc208405380
, 0xc20828e056, 0x5, 0x3a5f3, 0xc20803be90, 0x8efe20, 0xc20840d410, 0x1, 0x0, 
0x0, ...)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/variables.go:506 
+0x16dd
github.com/derekparker/delve/proc.(*EvalScope).extractValue(0xc208405380, 
0xc20828e056, 0x5, 0x3a5f3, 0x0, 0x8efe20, 0xc20840d410, 0x7f91f3e3c901, 0x0, 
0x0, ...)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/variables.go:469 
+0xb8
github.com/derekparker/delve/proc.(*EvalScope).extractVariableFromEntry(0xc20840
5380, 0xc20840d3b0, 0x0, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/variables.go:423 
+0x557
github.com/derekparker/delve/proc.(*EvalScope).variablesByTag(0xc208405380, 
0xc200000034, 0x0, 0x0, 0x0, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/variables.go:836 
+0x1ca
github.com/derekparker/delve/proc.(*EvalScope).LocalVariables(0xc208405380, 
0x0, 0x0, 0x0, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/variables.go:276 
+0x5d
github.com/derekparker/delve/service/debugger.(*Debugger).LocalVariables(0xc2080
2b3e0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/service/debugger/debugge
r.go:394 +0xf4
github.com/derekparker/delve/service/rpc.(*RPCServer).ListLocalVars(0xc20801f6e0
, 0xffffffffffffffff, 0x0, 0xc208405340, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/service/rpc/server.go:22
0 +0x5b
reflect.Value.call(0x87db20, 0x946fb0, 0x13, 0x963a80, 0x4, 0xc2085a9f28, 0x3, 
0x3, 0x0, 0x0, ...)
    /opt/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x87db20, 0x946fb0, 0x13, 0xc2085a9f28, 0x3, 0x3, 0x0, 0x0, 
0x0)
    /opt/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc208343b80, 0xc208343b40, 0xc208255800, 0xc208061200, 
0xc2082435a0, 0x8d2820, 0xc2083fecb0, 0xd9, 0x7c0b40, 0xc208405340, ...)
    /opt/go/src/net/rpc/server.go:382 +0x1f7
created by net/rpc.(*Server).ServeCodec
    /opt/go/src/net/rpc/server.go:476 +0x44a

goroutine 1 [chan receive]:
net/rpc.(*Client).Call(0xc20828c780, 0xc208405280, 0x17, 0x8d2820, 
0xc2083fec80, 0x7c0b40, 0xc208405260, 0x0, 0x0)
    /opt/go/src/net/rpc/client.go:315 +0xd6
github.com/derekparker/delve/service/rpc.(*RPCClient).call(0xc208242c00, 
0x990510, 0xd, 0x8d2820, 0xc2083fec80, 0x7c0b40, 0xc208405260, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/service/rpc/client.go:22
9 +0xb1
github.com/derekparker/delve/service/rpc.(*RPCClient).ListLocalVariables(0xc2082
42c00, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/service/rpc/client.go:18
4 +0x111
github.com/derekparker/delve/terminal.locals(0x7f91f3e543c0, 0xc208242c00, 
0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

/tank/home/user/gocode/src/github.com/derekparker/delve/terminal/command.go:555 
+0x87
github.com/derekparker/delve/terminal.func·005(0x7f91f3e543c0, 0xc208242c00, 
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/terminal/command.go:507 
+0xac
github.com/derekparker/delve/terminal.func·006(0x7f91f3e543c0, 0xc208242c00, 
0xc2083fec70, 0x0, 0x0, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/terminal/command.go:588 
+0x236
github.com/derekparker/delve/terminal.(*Term).Run(0xc208266390, 0x0, 0x0, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/terminal/terminal.go:85 
+0x9d5
main.execute(0x0, 0xc20801f640, 0x2, 0x2, 0xc208032068, 0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/cmd/dlv/main.go:312 
+0x4ea
main.func·003(0x0)

/tank/home/user/gocode/src/github.com/derekparker/delve/cmd/dlv/main.go:96 
+0x444
main.func·004(0xc20802c540, 0xc20802afe0, 0x1, 0x1)

/tank/home/user/gocode/src/github.com/derekparker/delve/cmd/dlv/main.go:97 +0x7a
github.com/spf13/cobra.(*Command).execute(0xc20802c540, 0xc20802af90, 0x1, 0x1, 
0x0, 0x0)
    /tank/home/user/gocode/src/github.com/spf13/cobra/command.go:501 +0x82f
github.com/spf13/cobra.(*Command).Execute(0xc20802c000, 0x0, 0x0)
    /tank/home/user/gocode/src/github.com/spf13/cobra/command.go:584 +0x414
main.main()

/tank/home/user/gocode/src/github.com/derekparker/delve/cmd/dlv/main.go:271 
+0xd75

goroutine 5 [syscall]:
os/signal.loop()
    /opt/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /opt/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc208070000)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/proc.go:689 +0x5d
created by github.com/derekparker/delve/proc.New
    /tank/home/user/gocode/src/github.com/derekparker/delve/proc/proc.go:69 
+0x218

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /opt/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 13 [chan receive]:
github.com/derekparker/delve/terminal.func·007()

/tank/home/user/gocode/src/github.com/derekparker/delve/terminal/terminal.go:42 
+0x6d
created by github.com/derekparker/delve/terminal.(*Term).Run

/tank/home/user/gocode/src/github.com/derekparker/delve/terminal/terminal.go:48 
+0x263

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc208010530, 0x72, 0x0, 0x0)
    /opt/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010530, 0x0, 0x0)
    /opt/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080104d0, 0xc20833a001, 0x5ff, 0x5ff, 0x0, 
0x7f91f3e49e80, 0xc2083fecf0)
    /opt/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208032088, 0xc20833a001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
    /opt/go/src/net/net.go:121 +0xdc
encoding/json.(*Decoder).readValue(0xc2080d8000, 0x417710, 0x0, 0x0)
    /opt/go/src/encoding/json/stream.go:124 +0x5e1
encoding/json.(*Decoder).Decode(0xc2080d8000, 0x89bae0, 0xc20828c740, 0x0, 0x0)
    /opt/go/src/encoding/json/stream.go:44 +0x7b
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc20828c720, 0xc208242b80, 
0x0, 0x0)
    /opt/go/src/net/rpc/jsonrpc/server.go:66 +0x9c
net/rpc.(*Server).readRequestHeader(0xc208343b40, 0x7f91f3e54340, 0xc20828c720, 
0x0, 0x0, 0xc208242b80, 0x411700, 0x0, 0x0)
    /opt/go/src/net/rpc/server.go:575 +0x97
net/rpc.(*Server).readRequest(0xc208343b40, 0x7f91f3e54340, 0xc20828c720, 
0xc208061200, 0xc2082435a0, 0x8d2820, 0x0, 0x0, 0x0, 0x0, ...)
    /opt/go/src/net/rpc/server.go:542 +0xa2
net/rpc.(*Server).ServeCodec(0xc208343b40, 0x7f91f3e54340, 0xc20828c720)
    /opt/go/src/net/rpc/server.go:461 +0x6d
github.com/derekparker/delve/service/rpc.func·002()

/tank/home/user/gocode/src/github.com/derekparker/delve/service/rpc/server.go:65
 +0x1c5
created by github.com/derekparker/delve/service/rpc.(*RPCServer).Run

/tank/home/user/gocode/src/github.com/derekparker/delve/service/rpc/server.go:66
 +0x18d

goroutine 12 [IO wait]:
net.(*pollDesc).Wait(0xc2080104c0, 0x72, 0x0, 0x0)
    /opt/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080104c0, 0x0, 0x0)
    /opt/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010460, 0xc20833a601, 0x5ff, 0x5ff, 0x0, 
0x7f91f3e49e80, 0xc2083fe440)
    /opt/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080320e0, 0xc20833a601, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
    /opt/go/src/net/net.go:121 +0xdc
encoding/json.(*Decoder).readValue(0xc2080d8180, 0xc208147f40, 0x0, 0x0)
    /opt/go/src/encoding/json/stream.go:124 +0x5e1
encoding/json.(*Decoder).Decode(0xc2080d8180, 0x89ba20, 0xc208061748, 0x0, 0x0)
    /opt/go/src/encoding/json/stream.go:44 +0x7b
net/rpc/jsonrpc.(*clientCodec).ReadResponseHeader(0xc208061700, 0xc2082664e0, 
0x0, 0x0)
    /opt/go/src/net/rpc/jsonrpc/client.go:75 +0xaf
net/rpc.(*Client).input(0xc20828c780)
    /opt/go/src/net/rpc/client.go:109 +0xb6
created by net/rpc.NewClientWithCodec
    /opt/go/src/net/rpc/client.go:201 +0xd0

goroutine 21 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc208070180)

/tank/home/user/gocode/src/github.com/derekparker/delve/proc/proc.go:689 +0x5d
created by github.com/derekparker/delve/proc.New
    /tank/home/user/gocode/src/github.com/derekparker/delve/proc/proc.go:69 
+0x218
3
abc
&{cba 10 11.10335}
user@computer:~/bitshark/testgdb$
```

**Comment by bitshark** [comment]
The problem is fixed when I revert to Delve version 0.5.0.beta

**Comment by bitshark** [comment]
But it is present in v0.8.1-alpha , v0.8.0-alpha, and v0.7.0-alpha.

**Comment by aarzilli** [comment]
The problem is that delve can't tell where the scope of variables begins and ends because that information is not saved inside the executable and the code that reads strings has problems dealing with uninitialised memory.
PR #207 has a workaround for this problem

**Comment by bitshark** [comment]
Interesting... I really wish the Go language spec would be updated to assist in debugging. Perhaps be adding that information in DWARF?  Does that support encoding variable locality information , I don't know.  It'd be nice if we had something analogous to how I can compile C code with the -g flag.

thanks
