### ISSUE TITLE
Getting a panic

### ISSUE THREAD

**Issue by tleyden** [derekparker/delve#292]
Steps to reproduce:

* Build delve on OSX with `export GO15VENDOREXPERIMENT=1` before running `CERT=delve-cert make install`
* Clone: `git clone --recursive https://github.com/couchbase/sync_gateway.git`
* Enable GO15VENDOREXPERIMENT: `export GO15VENDOREXPERIMENT=1`
* Build: `cd sync_gateway/ && ./build.sh`
* Run delve: `dlv exec ./bin/sync_gateway`
* Hit 'c' to continue

At this point it panics with this stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x42f993f]

goroutine 1 [running]:
reflect.typesByString(0xc8200af960, 0x11, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/type.go:1331 +0x15f
reflect.(*rtype).ptrTo(0x4593ca0, 0x40118a2)
	/usr/local/go/src/reflect/type.go:1063 +0x248
reflect.PtrTo(0x5664080, 0x4593ca0, 0x0, 0x0)
	/usr/local/go/src/reflect/type.go:1029 +0x4d
encoding/gob.implementsInterface(0x5664080, 0x4593ca0, 0x5664080, 0x46662e0, 0x0)
	/usr/local/go/src/encoding/gob/type.go:152 +0x121
encoding/gob.validUserType(0x5664080, 0x4593ca0, 0xc820077280, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/type.go:88 +0x2b6
encoding/gob.userType(0x5664080, 0x4593ca0, 0x479f438)
	/usr/local/go/src/encoding/gob/type.go:162 +0x2b
encoding/gob.newTypeObject(0x47bf6f0, 0xa, 0xc820077240, 0x5664080, 0x46d6a60, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/type.go:540 +0x153b
encoding/gob.getType(0x47bf6f0, 0xa, 0xc820077240, 0x5664080, 0x46d6a60, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/type.go:608 +0x11f
encoding/gob.getBaseType(0x47bf6f0, 0xa, 0x5664080, 0x471f760, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/type.go:595 +0x8c
encoding/gob.newTypeObject(0x47c11e0, 0x8, 0xc820077100, 0x5664080, 0x4730dc0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/type.go:546 +0x1623
encoding/gob.getType(0x47c11e0, 0x8, 0xc820077100, 0x5664080, 0x4730dc0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/type.go:608 +0x11f
encoding/gob.getBaseType(0x47c11e0, 0x8, 0x5664080, 0x4730dc0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/type.go:595 +0x8c
encoding/gob.buildTypeInfo(0xc820077100, 0x5664080, 0x4730dc0, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/type.go:725 +0x12e
encoding/gob.getTypeInfo(0xc820077100, 0x4730dc0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/type.go:712 +0xa7
encoding/gob.mustGetTypeInfo(0x5664080, 0x4730dc0, 0x5664080)
	/usr/local/go/src/encoding/gob/type.go:776 +0x3d
encoding/gob.init()
	/usr/local/go/src/encoding/gob/type.go:269 +0x1e94
``` 

[Full stack trace gist](https://gist.github.com/tleyden/5644b65bf794af123f77)

OTOH if I run the binary via `./bin/sync_gateway`, there is no panic, so it seems to be specific to running under the debugger.

System info:

* Delve version: 0.10.0-alpha
* go version go1.5.1 darwin/amd64
* OSX Yosemite

**Comment by derekparker** [comment]
@tleyden would you mind verifying that this is still an issue?

**Comment by tleyden** [comment]
@derekparker yup, will do.

**Comment by tleyden** [comment]
@derekparker I just retested and the problem is fixed!
