### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by antonikonovalov** [derekparker/delve#354]
when debug of gorilla mux

run from idea go plugin 0.11.1026 in idea 16 last  eap
```
/usr/local/go/bin/go build -o "/private/var/folders/rl/lgwhvbs905lg29n026_5b3t00000gn/T/Build main.go and rungo" -gcflags "-N -l" /Users/antoniko/go/src/gitlab.nct/msg/msg/src/cmd/regulus/main.go
"/Users/antoniko/Library/Application Support/IntelliJIdea16/Go/lib/dlv/mac/dlv" --listen=localhost:57925 --headless=true exec "/private/var/folders/rl/lgwhvbs905lg29n026_5b3t00000gn/T/Build main.go and rungo" --
```

GO version 1.5.3
Idea plugin last version 
```
goroutine 29 [running]:
github.com/derekparker/delve/proc.(*Thread).readMemory(0xc820310480, 0xc820016540, 0xfffffffffffffff9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/threads_darwin.go:108 +0x8d
github.com/derekparker/delve/proc.cacheMemory(0x4a4a178, 0xc820769110, 0xc820016540, 0xfffffffffffffff9, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/mem.go:42 +0xf2
github.com/derekparker/delve/proc.(*Variable).loadArrayValues(0xc820112c60, 0x1)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:996 +0xa6
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820112c60, 0x1)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:802 +0x939
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82009c540, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:816 +0x10de
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82009c000, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:784 +0xb72
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc82009c000)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:770 +0x2a
github.com/derekparker/delve/proc.(*EvalScope).extractVariableFromEntry(0xc82091d720, 0xc8208acb70, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:559 +0x98
github.com/derekparker/delve/proc.(*EvalScope).variablesByTag(0xc82091d720, 0xc800000005, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:1538 +0x174
github.com/derekparker/delve/proc.(*EvalScope).FunctionArguments(0xc82091d720, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:595 +0x46
github.com/derekparker/delve/service/debugger.(*Debugger).collectBreakpointInformation(0xc820106070, 0xc82030e5f0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/service/debugger/debugger.go:331 +0x630
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc820106070, 0xc820761c80, 0x18, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/service/debugger/debugger.go:256 +0x9ce
github.com/derekparker/delve/service/rpc.(*RPCServer).Command(0xc820017840, 0xc820761c80, 0xc82030e7d0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/service/rpc/server.go:96 +0x3f
reflect.Value.call(0x4549fc0, 0x462f2e0, 0x13, 0x464c428, 0x4, 0xc8207cbec8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x4549fc0, 0x462f2e0, 0x13, 0xc8207cbec8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0xb1
net/rpc.(*service).call(0xc820310380, 0xc820310340, 0xc820aa07f0, 0xc82081b780, 0xc8202b35e0, 0x447d940, 0xc820761c80, 0x16, 0x447d9a0, 0xc82030e7d0, ...)
	/usr/local/go/src/net/rpc/server.go:383 +0x1c1
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:477 +0x4ac

goroutine 1 [chan receive]:
main.execute(0x0, 0xc820019b80, 0x1, 0x4, 0xc82002e0f0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/cmd/dlv/main.go:354 +0x832
main.main.func5(0xc820104780, 0xc820019b80, 0x1, 0x4)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/cmd/dlv/main.go:127 +0x47
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc820104780, 0xc820019b40, 0x4, 0x4, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:547 +0x869
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc820104000, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:630 +0x46a
main.main()
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/cmd/dlv/main.go:304 +0xd0f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc82009c380)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/proc.go:667 +0xc3
created by github.com/derekparker/delve/proc.New
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/proc.go:75 +0x1d4

goroutine 9 [IO wait]:
net.runtime_pollWait(0x49fcc18, 0x72, 0xc820010150)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82062e4c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82062e4c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82062e460, 0xc820a3a400, 0x200, 0x200, 0x0, 0x49f7050, 0xc820010150)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82063c010, 0xc820a3a400, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc82006e340, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc82006e340, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc82006e340, 0x456b280, 0xc820a9c380, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc820a9c360, 0xc8202b36e0, 0x0, 0x0)
	/usr/local/go/src/net/rpc/jsonrpc/server.go:66 +0x7c
net/rpc.(*Server).readRequestHeader(0xc820310340, 0x49feb78, 0xc820a9c360, 0x0, 0x0, 0xc8202b36e0, 0xc8201f9c00, 0x0, 0x0)
	/usr/local/go/src/net/rpc/server.go:576 +0x90
net/rpc.(*Server).readRequest(0xc820310340, 0x49feb78, 0xc820a9c360, 0xc820310340, 0xc820aa07f0, 0xc82081b780, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/rpc/server.go:543 +0x8b
net/rpc.(*Server).ServeCodec(0xc820310340, 0x49feb78, 0xc820a9c360)
	/usr/local/go/src/net/rpc/server.go:462 +0x8c
github.com/derekparker/delve/service/rpc.(*RPCServer).Run.func1(0xc820017840)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/service/rpc/server.go:65 +0x485
created by github.com/derekparker/delve/service/rpc.(*RPCServer).Run
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/service/rpc/server.go:66 +0x118

goroutine 10 [select, locked to thread]:
runtime.gopark(0x47546d8, 0xc82083f728, 0x4653c00, 0x6, 0x4034f18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82083f728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82083f728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by OneOfOne** [comment]
I ran into the same bug, slightly different output:

	➜ dlv version; go version
	Delve Debugger
	Version: 0.10.0-alpha
	Build: 98ae684096d7fd15942bdee9c30f70a9a4f07613
	go version devel +32fa667 2016-01-16 03:14:41 +0200 linux/amd64

	Process restarted with PID 31440
	(dlv) threads
	* Thread 31440 at 0x45aad0 /usr/src/go/src/runtime/rt0_linux_amd64.s:8 _rt0_amd64_linux
	(dlv) bt
	panic: runtime error: makeslice: len out of range

	goroutine 1 [running]:
	strings.Repeat(0xaeaa70, 0x1, 0x8000000000000003, 0x0, 0x0)
			/usr/src/go/src/strings/strings.go:427 +0x5f
	github.com/derekparker/delve/terminal.printStack(0xc8203fc000, 0x1, 0x4, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/terminal/command.go:818 +0x104
	github.com/derekparker/delve/terminal.stackCommand(0xc8203d0fa0, 0x0, 0x0, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/terminal/command.go:756 +0x158
	github.com/derekparker/delve/terminal.(*Term).Run(0xc8203d0fa0, 0x0, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/terminal/terminal.go:113 +0xac4
	main.execute(0x0, 0xc8201427c0, 0x1, 0x1, 0xc820148048, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/cmd/dlv/main.go:350 +0x594
	main.main.func7.1(0xe3ee00, 0x0, 0x0, 0xc820148048, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/cmd/dlv/main.go:255 +0x50d
	main.main.func7(0xc82016eb40, 0xe3ee00, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/cmd/dlv/main.go:238 +0x3e
	github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc82016eb40, 0xe3ee00, 0x0, 0x0, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:547 +0x85a
	github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc82016e000, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:630 +0x46a
	main.main()
			/home/oneofone/code/go/src/github.com/derekparker/delve/cmd/dlv/main.go:304 +0xd3c

**Comment by OneOfOne** [comment]
Still the same, trying to run `bt` crashes.

```
➜ dlv version; go version
Delve Debugger
Version: 0.11.0-alpha
Build: d756eba13a4fbde34cea847276b3f5ce044ce916
go version devel +e970966 2016-01-27 22:50:37 +0000 linux/amd64

➜ dlv test -- -test.run=.
Type 'help' for list of commands.
(dlv) s
> _rt0_amd64_linux() /usr/src/go/src/runtime/rt0_linux_amd64.s:9
     4:
     5: #include "textflag.h"
     6:
     7: TEXT _rt0_amd64_linux(SB),NOSPLIT,$-8
     8:         LEAQ    8(SP), SI // argv
=>   9:         MOVQ    0(SP), DI // argc
    10:         MOVQ    $main(SB), AX
    11:         JMP     AX
    12:
    13: // When building with -buildmode=c-shared, this symbol is called when the shared
    14: // library is loaded.
(dlv) bt
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
strings.Repeat(0xaea2d0, 0x1, 0x8000000000000003, 0x0, 0x0)
        /usr/src/go/src/strings/strings.go:427 +0x5f
github.com/derekparker/delve/terminal.printStack(0xc8200949a0, 0x1, 0x4, 0x0, 0x0)
        /home/oneofone/code/go/src/github.com/derekparker/delve/terminal/command.go:828 +0x104
github.com/derekparker/delve/terminal.stackCommand(0xc8205be000, 0x0, 0x0, 0x0, 0x0)
        /home/oneofone/code/go/src/github.com/derekparker/delve/terminal/command.go:766 +0x158
github.com/derekparker/delve/terminal.(*Term).Run(0xc8205be000, 0x0, 0x0, 0x0)
        /home/oneofone/code/go/src/github.com/derekparker/delve/terminal/terminal.go:113 +0xac4
main.execute(0x0, 0xc8201441c0, 0x2, 0x2, 0xc8200300e0, 0x0)
        /home/oneofone/code/go/src/github.com/derekparker/delve/cmd/dlv/main.go:361 +0x594
main.main.func7.1(0xc8200dbac0, 0x1, 0x2, 0xc8200300e0, 0x0)
        /home/oneofone/code/go/src/github.com/derekparker/delve/cmd/dlv/main.go:266 +0x50d
main.main.func7(0xc820142b40, 0xc8200dbac0, 0x1, 0x2)
        /home/oneofone/code/go/src/github.com/derekparker/delve/cmd/dlv/main.go:245 +0x3e
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc820142b40, 0xc8200db9a0, 0x2, 0x2, 0x0, 0x0)
        /home/oneofone/code/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:547 +0x85a
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc820142000, 0x0, 0x0)
        /home/oneofone/code/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:630 +0x46a
main.main()
        /home/oneofone/code/go/src/github.com/derekparker/delve/cmd/dlv/main.go:315 +0xd5c
```

**Comment by aarzilli** [comment]
@OneOfOne the patch hasn't been merged in master yet, you would have to check out my branch to test it.

**Comment by derekparker** [comment]
@OneOfOne patch just landed, please pull, build and try again. Reopen if still an issue.

**Comment by OneOfOne** [comment]
Works perfectly, thank you.

**Comment by bubnenkoff** [comment]
Hm, I got same error on latest version of imposm. But I got it when second tasks was run.

**Comment by aarzilli** [comment]
@bubnenkoff this bug was fixed a long time ago, you should open a new issue with more details.
