### ISSUE TITLE
Panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by asampal** [derekparker/delve#384]
delve at commit fb7210934d7bba9b57ae5b7c7e73d34e2cab6631
Visual Studio Code 0.10.6, Windows 10 64 bit, vscode-go 0.6.22

When I place a breakpoint at `s := S{}` in the code below, the debug console shows: `panic : runtime error: makeslice: len out of range`.
```
package main

import (
	"fmt"
	"reflect"
)

func main() {
	type S struct {
		F string `species:"gopher" color:"blue"`
	}

	s := S{}
	st := reflect.TypeOf(s)
	field := st.Field(0)
	fmt.Println(field.Tag.Get("color"), field.Tag.Get("species"))
}
```

**Comment by aarzilli** [comment]
Can not reproduce on linux, tagging this as windows specific. 
@asampal: could you copy the stack trace here? Thank you
cc: @lukehoban.

**Comment by asampal** [comment]
here you go:
```
2016/01/30 16:40:52 debugger.go:55: launching process with args: [./debug]
2016/01/30 16:40:53 debugger.go:177: created breakpoint: &api.Breakpoint{ID:1, Addr:0x401069, File:"d:/dev/projects/_go/src/github.com/asampal/hello/hello.go", Line:13, FunctionName:"main.main", Tracepoint:false, Stacktrace:0, Goroutine:false, Variables:[]string(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2016/01/30 16:40:53 debugger.go:239: continuing
panic: runtime error: makeslice: len out of range

goroutine 88 [running]:
github.com/derekparker/delve/proc.(*Thread).readMemory(0xc08216e1e0, 0x135860f10613b48, 0x1d90ac589d800000, 0x0, 0x0, 0x0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/threads_windows.go:156 +0xa3
github.com/derekparker/delve/proc.(*memCache).readMemory(0xc082193890, 0x135860f10613b48, 0x1d90ac589d800000, 0x0, 0x0, 0x0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/mem.go:27 +0x1df
github.com/derekparker/delve/proc.(*memCache).readMemory(0xc082365e30, 0x135860f10613b48, 0x1d90ac589d800000, 0x0, 0x0, 0x0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/mem.go:27 +0x1df
github.com/derekparker/delve/proc.cacheMemory(0x3f87088, 0xc082365f50, 0x135860f10613b48, 0x1d90ac589d800000, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/mem.go:45 +0x117
github.com/derekparker/delve/proc.(*Variable).loadArrayValues(0xc082090cb0, 0x2)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:938 +0xad
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc082090cb0, 0x2)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:744 +0x940
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc08216d6c0, 0x1)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:758 +0x1277
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc0820a7370, 0x1)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:724 +0xd0b
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc08216c460, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:758 +0x1277
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc08216c1c0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:724 +0xd0b
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc08216c000, 0x0, 0x1)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:1463 +0xe49
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc08216c000, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:763 +0xbc5
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc08216c000)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:710 +0x31
github.com/derekparker/delve/proc.(*EvalScope).extractVariableFromEntry(0xc0820be8e0, 0xc082193020, 0x0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:499 +0x9f
github.com/derekparker/delve/proc.(*EvalScope).variablesByTag(0xc0820be8e0, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:1484 +0x17b
github.com/derekparker/delve/proc.(*EvalScope).LocalVariables(0xc0820be8e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:530 +0x4d
github.com/derekparker/delve/service/debugger.(*Debugger).LocalVariables(0xc082164070, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/service/debugger/debugger.go:434 +0xc1
github.com/derekparker/delve/service/rpc.(*RPCServer).ListLocalVars(0xc08216a0c0, 0x1, 0x0, 0xc0820be880, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/service/rpc/server.go:231 +0x59
reflect.Value.call(0x97dfc0, 0xa68e30, 0x13, 0xa88f68, 0x4, 0xc082371ec8, 0x3, 0x3, 0x0, 0x0, ...)
	c:/go/src/reflect/value.go:432 +0x1211
reflect.Value.Call(0x97dfc0, 0xa68e30, 0x13, 0xc082371ec8, 0x3, 0x3, 0x0, 0x0, 0x0)
	c:/go/src/reflect/value.go:300 +0xb8
net/rpc.(*service).call(0xc082168c80, 0xc082168c40, 0xc0820ada10, 0xc0820f5180, 0xc0826980a0, 0x9d5b60, 0xc082130760, 0xd9, 0x8a6d60, 0xc0820be880, ...)
	c:/go/src/net/rpc/server.go:383 +0x1c8
created by net/rpc.(*Server).ServeCodec
	c:/go/src/net/rpc/server.go:477 +0x4b3

goroutine 1 [chan receive]:
main.execute(0x0, 0xc082164010, 0x1, 0x1, 0xc0820ee040, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/cmd/dlv/main.go:365 +0x839
main.main.func3.1(0xc0820eac00, 0x0, 0x3, 0xc0820ee040, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/cmd/dlv/main.go:116 +0x463
main.main.func3(0xc08211a5a0, 0xc0820eac00, 0x0, 0x3)
	d:/dev/projects/_go/src/github.com/derekparker/delve/cmd/dlv/main.go:100 +0x45
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc08211a5a0, 0xc0820eaae0, 0x3, 0x3, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:547 +0x870
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc08211a000, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:630 +0x59a
main.main()
	d:/dev/projects/_go/src/github.com/derekparker/delve/cmd/dlv/main.go:315 +0xd41
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	c:/go/src/runtime/asm_amd64.s:1721 +0x1
goroutine 5 [syscall]:
os/signal.loop()
	c:/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
	c:/go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 34 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc08216c380)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/proc.go:756 +0xd8
created by github.com/derekparker/delve/proc.New
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/proc.go:78 +0x1db
goroutine 82 [IO wait]:
net.runtime_pollWait(0x3fc0f18, 0x72, 0xc082130820)
	c:/go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc082736470, 0x72, 0x0, 0x0)
	c:/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082172000, 0xc082736360, 0xa8b778, 0x7, 0xb95f58, 0xc082130770, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:182 +0x177
net.(*netFD).Read(0xc082736300, 0xc08219c600, 0x200, 0x200, 0x0, 0x0, 0x0)
	c:/go/src/net/fd_windows.go:463 +0x17e
net.(*conn).Read(0xc0820ee028, 0xc08219c600, 0x200, 0x200, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:172 +0xeb
encoding/json.(*Decoder).refill(0xc0820421a0, 0x0, 0x0)
	c:/go/src/encoding/json/stream.go:152 +0x28e
encoding/json.(*Decoder).readValue(0xc0820421a0, 0x1, 0x0, 0x0)
	c:/go/src/encoding/json/stream.go:128 +0x422
encoding/json.(*Decoder).Decode(0xc0820421a0, 0x99f940, 0xc08218b700, 0x0, 0x0)
	c:/go/src/encoding/json/stream.go:57 +0x160
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc08218b6e0, 0xc082195e60, 0x0, 0x0)
	c:/go/src/net/rpc/jsonrpc/server.go:66 +0x83
net/rpc.(*Server).readRequestHeader(0xc082168c40, 0x4ec06c0, 0xc08218b6e0, 0x0, 0x0, 0xc082195e60, 0xc082779c00, 0x0, 0x0)
	c:/go/src/net/rpc/server.go:576 +0x97
net/rpc.(*Server).readRequest(0xc082168c40, 0x4ec06c0, 0xc08218b6e0, 0xc082168c40, 0xc0820ada10, 0xc0820f5180, 0x0, 0x0, 0x0, 0x0, ...)
	c:/go/src/net/rpc/server.go:543 +0x92
net/rpc.(*Server).ServeCodec(0xc082168c40, 0x4ec06c0, 0xc08218b6e0)
	c:/go/src/net/rpc/server.go:462 +0x93
github.com/derekparker/delve/service/rpc.(*ServerImpl).Run.func1(0xc082172018)
	d:/dev/projects/_go/src/github.com/derekparker/delve/service/rpc/server.go:71 +0x4a6
created by github.com/derekparker/delve/service/rpc.(*ServerImpl).Run
	d:/dev/projects/_go/src/github.com/derekparker/delve/service/rpc/server.go:72 +0x129
```

**Comment by lukehoban** [comment]
Strange.

I can confirm that this only appears to repro on Windows, I wasn't able to repro on OSX either.

The repro steps are:

```
b hello.go:13
c
locals
```

What's odd is that just making the following change, which should have no operational impact on the code (and doesn't appear to have any significant unexpected impact on the compiled instructions), causes the error to not occur.

```go
package main

import (
    "fmt"
    "reflect"
)

func main() {
    type S struct {
        F string `species:"gopher" color:"blue"`
    }

    s := S{}
    st := reflect.TypeOf(s)
    field := st.Field(0)
    _ = field.Tag.Get("color") // Add this line
    fmt.Println(field.Tag.Get("color"), field.Tag.Get("species"))
}
```

I'll try to narrow this down further...

**Comment by lukehoban** [comment]
So the problem also only occurs when the breakpoint it before `st` is initialized, so it's related to eval'ing that local when it's in an uninitialized state.

Adding some tracing, I see the following in the case where it doesn't fail:

```
(dlv) locals
extractVariableFromEntry:  st
extractVariableFromEntry:  &{826814971416 false st reflect.Type reflect.Type interface 0xc0820e42d0 0xc082158000 <nil> 0 0 0 0 <nil> 0 [] false <nil>}
loadValueInternal:  st
loadValueInternal:  interface
loadInterface: realType:  reflect.Type
loadInterface: ityp:  struct runtime.iface
loadInterface: f.Name:  tab
loadInterface: tab:  &{826814971416 false st.tab *runtime.itab *runtime.itab ptr 0xc08235ca80 0xc082158000 <nil> 0 0 0 0 <nil> 0 [] false <nil>}
loadInterface: _type:  &{6946824 false st.tab._type *runtime._type *runtime._type ptr 0xc08235ca80 0xc082158000 <nil> 0 0 0 0 <nil> 0 [] false <nil>}
loadInterface: typestring:  &{584 false st.tab._type._string *string *string ptr 0xc08235ca80 0xc082158000 <nil> 0 0 0 0 <nil> 0 [] false <nil>}
loadInterface: typestring:  &{0 false  string string string 0xc08235ca80 0xc082158000 <nil> 0 0 0 1 0xc082636740 0 [] false could not read memory}
loadInterface: f.Name:  data
loadInterface: isnil:  false
loadInterface: typestring:  &{0 false  string string string 0xc08235ca80 0xc082158000 <nil> 0 0 0 1 0xc082636740 0 [] false could not read memory}
```

And this in the case where it does fail:

```

(dlv) locals
extractVariableFromEntry:  st
extractVariableFromEntry:  &{826814971432 false st reflect.Type reflect.Type interface 0xc08200cdc0 0xc082080460 <nil> 0 0 0 0 <nil> 0 [] false <nil>}
loadValueInternal:  st
loadValueInternal:  interface
loadInterface: realType:  reflect.Type
loadInterface: ityp:  struct runtime.iface
loadInterface: f.Name:  tab
loadInterface: tab:  &{826814971432 false st.tab *runtime.itab *runtime.itab ptr 0xc082716a80 0xc082080460 <nil> 0 0 0 0 <nil> 0 [] false <nil>}
loadInterface: _type:  &{7225520 false st.tab._type *runtime._type *runtime._type ptr 0xc082716a80 0xc082080460 <nil> 0 0 0 0 <nil> 0 [] false <nil>}
loadInterface: typestring:  &{5322280 false st.tab._type._string *string *string ptr 0xc082716a80 0xc082080460 <nil> 0 0 0 0 <nil> 0 [] false <nil>}
loadInterface: typestring:  &{5381696 false  string string string 0xc082716a80 0xc082080460 <nil> 14 0 5359088 1 0xc0821d2880 0 [] false <nil>}
loadInterface: f.Name:  data
loadInterface: isnil:  false
loadInterface: typestring:  &{5381696 false  string string string 0xc082716a80 0xc082080460 <nil> 14 0 5359088 1 0xc0821d2880 0 [] false <nil>}

// starts diverging here...

loadValueInternal:
loadValueInternal:  string
loadInterface: t:  &{1 0xc082678b80}
loadInterface: typ:  *struct reflect.rtype
loadInterface: realtyp:  *struct reflect.rtype
loadInterface: data:  &{826814971440 false st.data *void *void unsafe.Pointer 0xc08263ecf0 0xc08211c0e0 <nil> 0 0 0 0 <nil> 0 [] false <nil>}
loadInterface: datanew:  &{826814971440 false data *struct reflect.rtype *struct reflect.rtype ptr 0xc08263ecf0 0xc08211c0e0 <nil> 0 0 0 0 <nil> 0 [] false <nil>}
loadValueInternal:  data
loadValueInternal:  ptr
loadValueInternal:
loadValueInternal:  struct
loadValueInternal:  size
loadValueInternal:  uint
loadValueInternal:  ptrdata
loadValueInternal:  uint
loadValueInternal:  hash
loadValueInternal:  uint
loadValueInternal:  _
loadValueInternal:  uint
loadValueInternal:  align
loadValueInternal:  uint
loadValueInternal:  fieldAlign
loadValueInternal:  uint
loadValueInternal:  kind
loadValueInternal:  uint
loadValueInternal:  alg
loadValueInternal:  ptr
loadValueInternal:
loadValueInternal:  struct
early return
loadValueInternal:  gcdata
loadValueInternal:  ptr
loadValueInternal:
loadValueInternal:  uint
loadValueInternal:  string
loadValueInternal:  ptr
loadValueInternal:
loadValueInternal:  string
loadValueInternal:  *reflect.uncommonType
loadValueInternal:  ptr
loadValueInternal:
loadValueInternal:  struct
loadValueInternal:  name
loadValueInternal:  ptr
loadValueInternal:
loadValueInternal:  string
early return
loadValueInternal:  pkgPath
loadValueInternal:  ptr
loadValueInternal:
loadValueInternal:  string
early return
loadValueInternal:
loadValueInternal:  int
loadValueInternal:
loadValueInternal:  int
loadValueInternal:  methods
loadValueInternal:  slice
loadArrayValues:  methods
loadArrayValues:  &{4643152 false methods []struct reflect.method []struct reflect.method slice 0xc08209ef60 0xc082180000 <nil> -8410374531276341248 -1641200405627001780 87123167061031752 48 0xc082167ac0 0 [] true <nil>}
panic: runtime error: makeslice: len out of range
```

In the first case, `typestring.Addr == 0` causes `loadInterface` to fail with `"invalid interface type"`.  In the second case though, `typeString.Addr` doesn't end up being 0, and starts diverging.  

Ultimately, the crash happens when trying to load the `(reflect.uncommonType).methods` slice.  The data is completely bogus here - with a `v.Len` of ` -8410374531276341248 `.

I'm not familiar with where the variable loading code is supposed to be guarding against this.  But it's not clearly this is a problem unique to Windows, just that the particular bogus uninitialized data with this specific code on Windows is triggering a path through this logic that isn't getting caught as `Unreadable` early enough.

@aarzilli Maybe you have a guess about what's needed here?

**Comment by aarzilli** [comment]
Go doesn't export detailed variable scope information so sometimes we end up reading uninitialized memory, that's expected. 

The issue here is that v.Len is a very large negative number that overflows the size argument of cacheMemory. This problem was introduced by my memory prefetch patch, the check can otherwise be implicit.
