### ISSUE TITLE
panic: runtime error: invalid memory on step command

### ISSUE THREAD

**Issue by krhubert** [derekparker/delve#414]
```
(dlv) s
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5ee57c]

goroutine 84 [running]:
github.com/derekparker/delve/proc.(*Thread).singleStep(0xc8205e9810, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/threads_linux.go:52 +0x1ac
github.com/derekparker/delve/proc.(*Thread).StepInstruction(0xc8205e9810, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/threads.go:96 +0x1a7
github.com/derekparker/delve/proc.(*Process).Step.func1(0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/proc.go:481 +0x8f
github.com/derekparker/delve/proc.(*Process).run(0xc8207600e0, 0xc820055868, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/proc.go:771 +0x12a
github.com/derekparker/delve/proc.(*Process).Step(0xc8207600e0, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/proc.go:497 +0x53
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc82000ddc0, 0xc82050c100, 0x7fa286ae4000, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/service/debugger/debugger.go:284 +0x5a6
github.com/derekparker/delve/service/rpc.(*RPCServer).Command(0xc82000f6a0, 0xc82050c100, 0xc82050e0a0, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/service/rpc/server.go:107 +0x3f
reflect.Value.call(0x944f40, 0xa297c0, 0x13, 0xa47938, 0x4, 0xc820055ee8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x944f40, 0xa297c0, 0x13, 0xc820055ee8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0xb1
net/rpc.(*service).call(0xc8204585c0, 0xc820458580, 0xc820491480, 0xc82008eb80, 0xc82048fc20, 0x878440, 0xc82050c100, 0x16, 0x8784a0, 0xc82050e0a0, ...)
	/usr/local/go/src/net/rpc/server.go:383 +0x1c1
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:477 +0x4ac

goroutine 1 [chan receive]:
net/rpc.(*Client).Call(0xc820116120, 0xc82050c060, 0x11, 0x878440, 0xc82050c040, 0x8784a0, 0xc82050e000, 0x0, 0x0)
	/usr/local/go/src/net/rpc/client.go:315 +0xcd
github.com/derekparker/delve/service/rpc.(*RPCClient).call(0xc82010c200, 0xa47ae0, 0x7, 0x878440, 0xc82050c040, 0x8784a0, 0xc82050e000, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/service/rpc/client.go:254 +0xb4
github.com/derekparker/delve/service/rpc.(*RPCClient).Step(0xc82010c200, 0xb4f980, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/service/rpc/client.go:100 +0xcc
github.com/derekparker/delve/terminal.step(0xc82020ad70, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/terminal/command.go:467 +0x4c
github.com/derekparker/delve/terminal.(*Term).Run(0xc82020ad70, 0x0, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/terminal/terminal.go:117 +0xab2
main.execute(0x0, 0xc82000d950, 0x1, 0x1, 0xc820026088, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/cmd/dlv/main.go:362 +0x807
main.init.1.func4(0xc82011c800, 0xc82000d950, 0x1, 0x1)
	/usr/src/go/src/github.com/derekparker/delve/cmd/dlv/main.go:119 +0x4a
github.com/spf13/cobra.(*Command).execute(0xc82011c800, 0xc82000d8e0, 0x1, 0x1, 0x0, 0x0)
	/usr/src/go/src/github.com/spf13/cobra/command.go:569 +0x869
github.com/spf13/cobra.(*Command).ExecuteC(0xc82011c000, 0xc82011c800, 0x0, 0x0)
	/usr/src/go/src/github.com/spf13/cobra/command.go:656 +0x56b
github.com/spf13/cobra.(*Command).Execute(0xc82011c000, 0x0, 0x0)
	/usr/src/go/src/github.com/spf13/cobra/command.go:615 +0x2d
main.main()
	/usr/src/go/src/github.com/derekparker/delve/cmd/dlv/main.go:186 +0x3c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [select, locked to thread]:
runtime.gopark(0xb502e0, 0xc820024728, 0xa4f0b0, 0x6, 0x430e18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820024728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820024728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 55 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc8207600e0)
	/usr/src/go/src/github.com/derekparker/delve/proc/proc.go:783 +0xc3
created by github.com/derekparker/delve/proc.New
	/usr/src/go/src/github.com/derekparker/delve/proc/proc.go:78 +0x1d4

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7fa2869395d8, 0x72, 0xc82000c1b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820015a30, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820015a30, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200159d0, 0xc8204c4001, 0x5ff, 0x5ff, 0x0, 0x7fa286934050, 0xc82000c1b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026120, 0xc8204c4001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc82005dd40, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc82005dd40, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc82005dd40, 0x966aa0, 0xc820493280, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc820493260, 0xc82010ca00, 0x0, 0x0)
	/usr/local/go/src/net/rpc/jsonrpc/server.go:66 +0x7c
net/rpc.(*Server).readRequestHeader(0xc820458580, 0x7fa286946530, 0xc820493260, 0x0, 0x0, 0xc82010ca00, 0xc820053c00, 0x0, 0x0)
	/usr/local/go/src/net/rpc/server.go:576 +0x90
net/rpc.(*Server).readRequest(0xc820458580, 0x7fa286946530, 0xc820493260, 0xc820458580, 0xc820491480, 0xc82008eb80, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/rpc/server.go:543 +0x8b
net/rpc.(*Server).ServeCodec(0xc820458580, 0x7fa286946530, 0xc820493260)
	/usr/local/go/src/net/rpc/server.go:462 +0x8c
github.com/derekparker/delve/service/rpc.(*ServerImpl).Run.func1(0xc8200260c8)
	/usr/src/go/src/github.com/derekparker/delve/service/rpc/server.go:72 +0x4f9
created by github.com/derekparker/delve/service/rpc.(*ServerImpl).Run
	/usr/src/go/src/github.com/derekparker/delve/service/rpc/server.go:73 +0x122

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7fa286939698, 0x72, 0xc82000c1b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200159c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200159c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820015960, 0xc8207e8001, 0xdff, 0xdff, 0x0, 0x7fa286934050, 0xc82000c1b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82010a050, 0xc8207e8001, 0xdff, 0xdff, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc820496000, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc820496000, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc820496000, 0x9669e0, 0xc820110148, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*clientCodec).ReadResponseHeader(0xc820110100, 0xc820494750, 0x0, 0x0)
	/usr/local/go/src/net/rpc/jsonrpc/client.go:75 +0x8f
net/rpc.(*Client).input(0xc820116120)
	/usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
	/usr/local/go/src/net/rpc/client.go:201 +0xd2

goroutine 20 [chan receive]:
github.com/derekparker/delve/terminal.(*Term).Run.func1(0xc820116360, 0xc82020ad70)
	/usr/src/go/src/github.com/derekparker/delve/terminal/terminal.go:56 +0x77
created by github.com/derekparker/delve/terminal.(*Term).Run
	/usr/src/go/src/github.com/derekparker/delve/terminal/terminal.go:62 +0x1c2
```

**Comment by derekparker** [comment]
@krhubert can you provide some more information along the lines of steps to reproduce? What `s` the first command you entered into the Delve prompt?

**Comment by krhubert** [comment]
@derekparker  here you go. I will try to reduce step to reprocue it.

source code [math.go]
```
package main

import "math"

var f = 1.5

func main() {
	_ = math.Floor(f)
	_ = float64(int(f))
}
```
build
```
go build math.go
```

debugging
```
dlv exec ./math
(dlv) help
The following commands are available:
    help ------------------------ Prints the help message.
    break (alias: b) ------------ break <linespec> [-stack <n>|-goroutine|<variable name>]*
    trace (alias: t) ------------ Set tracepoint, takes the same arguments as break.
    restart (alias: r) ---------- Restart process.
    continue (alias: c) --------- Run until breakpoint or program termination.
    step (alias: s) ------------- Single step through program.
    step-instruction (alias: si)  Single step a single cpu instruction.
    next (alias: n) ------------- Step over to next source line.
    threads --------------------- Print out info for every traced thread.
    thread (alias: tr) ---------- Switch to the specified thread.
    clear ----------------------- Deletes breakpoint.
    clearall -------------------- clearall [<linespec>]. Deletes all breakpoints. If <linespec> is provided, only matching breakpoints will be deleted.
    goroutines ------------------ goroutines [-u (default: user location)|-r (runtime location)|-g (go statement location)] Print out info for every goroutine.
    goroutine ------------------- Sets current goroutine.
    breakpoints (alias: bp) ----- Print out info for active breakpoints.
    print (alias: p) ------------ Evaluate a variable.
    set ------------------------- Changes the value of a variable.
    sources --------------------- Print list of source files, optionally filtered by a regexp.
    funcs ----------------------- Print list of functions, optionally filtered by a regexp.
    args ------------------------ Print function arguments, optionally filtered by a regexp.
    locals ---------------------- Print function locals, optionally filtered by a regexp.
    vars ------------------------ Print package variables, optionally filtered by a regexp.
    regs ------------------------ Print contents of CPU registers.
    exit (alias: quit | q) ------ Exit the debugger.
    list (alias: ls) ------------ list <linespec>.  Show source around current point or provided linespec.
    stack (alias: bt) ----------- stack [<depth>] [-full]. Prints stack.
    frame ----------------------- Sets current stack frame (0 is the top of the stack)
    source ---------------------- Executes a file containing a list of delve commands
(dlv) break main.go:1-0
Command failed: Malformed breakpoint location "main.go:1-0" at 8: line offset negative or not a number
(dlv) break main.go:10
Command failed: Location "main.go:10" not found
(dlv) break math.go:9
Breakpoint 1 set at 0x401031 for main.main ./math.go:9
(dlv) c
> main.main() ./math.go:9 (hits goroutine(1):1 total:1)
     4:	
     5:	var f = 1.5
     6:	
     7:	func main() {
     8:		_ = math.Floor(f)
=>   9:		_ = float64(int(f))
    10:	}
(dlv) s
> main.main() ./math.go:10
     5:	var f = 1.5
     6:	
     7:	func main() {
     8:		_ = math.Floor(f)
     9:		_ = float64(int(f))
=>  10:	}
(dlv) s
> runtime.main() /usr/local/go/src/runtime/proc.go:120
   115:	
   116:		// Make racy client program work: if panicking on
   117:		// another goroutine at the same time as main returns,
   118:		// let the other goroutine finish printing the panic trace.
   119:		// Once it does, it will exit. See issue 3934.
=> 120:		if panicking != 0 {
   121:			gopark(nil, nil, "panicwait", traceEvGoStop, 1)
   122:		}
   123:	
   124:		exit(0)
   125:		for {
(dlv) c
Process 3712 has exited with status 0
(dlv) break math.go:8
Process 0 has exited with status 0
(dlv) restart
Process restarted with PID 4316
(dlv) c
> main.main() ./math.go:9 (hits goroutine(1):1 total:1)
     4:	
     5:	var f = 1.5
     6:	
     7:	func main() {
     8:		_ = math.Floor(f)
=>   9:		_ = float64(int(f))
    10:	}
(dlv) s
> main.main() ./math.go:10
     5:	var f = 1.5
     6:	
     7:	func main() {
     8:		_ = math.Floor(f)
     9:		_ = float64(int(f))
=>  10:	}
(dlv) s
> runtime.main() /usr/local/go/src/runtime/proc.go:120
   115:	
   116:		// Make racy client program work: if panicking on
   117:		// another goroutine at the same time as main returns,
   118:		// let the other goroutine finish printing the panic trace.
   119:		// Once it does, it will exit. See issue 3934.
=> 120:		if panicking != 0 {
   121:			gopark(nil, nil, "panicwait", traceEvGoStop, 1)
   122:		}
   123:	
   124:		exit(0)
   125:		for {
(dlv) c
Process 4316 has exited with status 0
(dlv) break math.go:7
Process 0 has exited with status 0
(dlv) break math.go:7
Process 0 has exited with status 0
(dlv) restart
Process restarted with PID 4394
(dlv) break math.go:7
Breakpoint 2 set at 0x401000 for main.main ./math.go:7
(dlv) c
> main.main() ./math.go:7 (hits goroutine(1):1 total:1)
     2:	
     3:	import "math"
     4:	
     5:	var f = 1.5
     6:	
=>   7:	func main() {
     8:		_ = math.Floor(f)
     9:		_ = float64(int(f))
    10:	}
(dlv) s
> main.main() ./math.go:8
     3:	import "math"
     4:	
     5:	var f = 1.5
     6:	
     7:	func main() {
=>   8:		_ = math.Floor(f)
     9:		_ = float64(int(f))
    10:	}
(dlv) s
Stopped at: 0x44eb20
=>no source available
(dlv) s
Stopped at: 0x44eb25
=>no source available
(dlv) s
Stopped at: 0x44eb2f
=>no source available
(dlv) s
Stopped at: 0x44eb32
=>no source available
(dlv) s
Stopped at: 0x44eb36
=>no source available
(dlv) c
> main.main() ./math.go:9 (hits goroutine(1):1 total:1)
     4:	
     5:	var f = 1.5
     6:	
     7:	func main() {
     8:		_ = math.Floor(f)
=>   9:		_ = float64(int(f))
    10:	}
(dlv) s
> main.main() ./math.go:10
     5:	var f = 1.5
     6:	
     7:	func main() {
     8:		_ = math.Floor(f)
     9:		_ = float64(int(f))
=>  10:	}
(dlv) s
> runtime.main() /usr/local/go/src/runtime/proc.go:120
   115:	
   116:		// Make racy client program work: if panicking on
   117:		// another goroutine at the same time as main returns,
   118:		// let the other goroutine finish printing the panic trace.
   119:		// Once it does, it will exit. See issue 3934.
=> 120:		if panicking != 0 {
   121:			gopark(nil, nil, "panicwait", traceEvGoStop, 1)
   122:		}
   123:	
   124:		exit(0)
   125:		for {
(dlv) c
Process 4394 has exited with status 0
(dlv) restart
Process restarted with PID 4472
(dlv) c
> main.main() ./math.go:7 (hits goroutine(1):1 total:1)
     2:	
     3:	import "math"
     4:	
     5:	var f = 1.5
     6:	
=>   7:	func main() {
     8:		_ = math.Floor(f)
     9:		_ = float64(int(f))
    10:	}
(dlv) s
> main.main() ./math.go:8
     3:	import "math"
     4:	
     5:	var f = 1.5
     6:	
     7:	func main() {
=>   8:		_ = math.Floor(f)
     9:		_ = float64(int(f))
    10:	}
(dlv) s
Stopped at: 0x44eb20
=>no source available
(dlv) s
Stopped at: 0x44eb25
=>no source available
(dlv) s
Stopped at: 0x44eb2f
=>no source available
(dlv) s
Stopped at: 0x44eb32
=>no source available
(dlv) s
Stopped at: 0x44eb36
=>no source available
(dlv) s
Stopped at: 0x44eb40
=>no source available
(dlv) s
Stopped at: 0x44eb43
=>no source available
(dlv) 
Stopped at: 0x44eb45
=>no source available
(dlv) 
Stopped at: 0x44eb4a
=>no source available
(dlv) 
Stopped at: 0x44eb4f
=>no source available
(dlv) 
Stopped at: 0x44eb54
=>no source available
(dlv) 
Stopped at: 0x44eb59
=>no source available
(dlv) 
Stopped at: 0x44eb61
=>no source available
(dlv) 
Stopped at: 0x44eb65
=>no source available
(dlv) 
Stopped at: 0x44eb69
=>no source available
(dlv) 
Stopped at: 0x44eb6f
=>no source available
(dlv) 
> main.main() ./math.go:8
     3:	import "math"
     4:	
     5:	var f = 1.5
     6:	
     7:	func main() {
=>   8:		_ = math.Floor(f)
     9:		_ = float64(int(f))
    10:	}
(dlv) 
> main.main() ./math.go:9
     4:	
     5:	var f = 1.5
     6:	
     7:	func main() {
     8:		_ = math.Floor(f)
=>   9:		_ = float64(int(f))
    10:	}
(dlv) 
> main.main() ./math.go:10
     5:	var f = 1.5
     6:	
     7:	func main() {
     8:		_ = math.Floor(f)
     9:		_ = float64(int(f))
=>  10:	}
(dlv) 
> runtime.main() /usr/local/go/src/runtime/proc.go:120
   115:	
   116:		// Make racy client program work: if panicking on
   117:		// another goroutine at the same time as main returns,
   118:		// let the other goroutine finish printing the panic trace.
   119:		// Once it does, it will exit. See issue 3934.
=> 120:		if panicking != 0 {
   121:			gopark(nil, nil, "panicwait", traceEvGoStop, 1)
   122:		}
   123:	
   124:		exit(0)
   125:		for {
(dlv) 
> runtime.main() /usr/local/go/src/runtime/proc.go:124
   119:		// Once it does, it will exit. See issue 3934.
   120:		if panicking != 0 {
   121:			gopark(nil, nil, "panicwait", traceEvGoStop, 1)
   122:		}
   123:	
=> 124:		exit(0)
   125:		for {
   126:			var x *int32
   127:			*x = 0
   128:		}
   129:	}
(dlv) 
> runtime.exit() /usr/local/go/src/runtime/sys_linux_amd64.s:14
     9:	#include "go_asm.h"
    10:	#include "go_tls.h"
    11:	#include "textflag.h"
    12:	
    13:	TEXT runtime·exit(SB),NOSPLIT,$0-4
=>  14:		MOVL	code+0(FP), DI
    15:		MOVL	$231, AX	// exitgroup - force all os threads to exit
    16:		SYSCALL
    17:		RET
    18:	
    19:	TEXT runtime·exit1(SB),NOSPLIT,$0-4
(dlv) 
> runtime.exit() /usr/local/go/src/runtime/sys_linux_amd64.s:15
    10:	#include "go_tls.h"
    11:	#include "textflag.h"
    12:	
    13:	TEXT runtime·exit(SB),NOSPLIT,$0-4
    14:		MOVL	code+0(FP), DI
=>  15:		MOVL	$231, AX	// exitgroup - force all os threads to exit
    16:		SYSCALL
    17:		RET
    18:	
    19:	TEXT runtime·exit1(SB),NOSPLIT,$0-4
    20:		MOVL	code+0(FP), DI
(dlv) 
> runtime.exit() /usr/local/go/src/runtime/sys_linux_amd64.s:16
    11:	#include "textflag.h"
    12:	
    13:	TEXT runtime·exit(SB),NOSPLIT,$0-4
    14:		MOVL	code+0(FP), DI
    15:		MOVL	$231, AX	// exitgroup - force all os threads to exit
=>  16:		SYSCALL
    17:		RET
    18:	
    19:	TEXT runtime·exit1(SB),NOSPLIT,$0-4
    20:		MOVL	code+0(FP), DI
    21:		MOVL	$60, AX	// exit - exit the current os thread
(dlv) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5ee57c]

goroutine 165 [running]:
github.com/derekparker/delve/proc.(*Thread).singleStep(0xc8203e0280, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/threads_linux.go:52 +0x1ac
github.com/derekparker/delve/proc.(*Thread).StepInstruction(0xc8203e0280, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/threads.go:96 +0x1a7
...
```
