### ISSUE TITLE
panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by asampal** [derekparker/delve#416]
Windows 10 64 bit, Visual Studio Code 0.10.8, dlv 3360a2e997bf0554e840dde1b83422fabce11ae2

When I run the following code, it completes with the expected output. If I insert a breakpoint on line 15, `field := st.Field(0)`, the panic in the title happens.

```
package main

import (
	"fmt"
	"reflect"
)

func main() {
	type S struct {
		F string `species:"gopher" color:"blue"`
	}

	s := S{}
	st := reflect.TypeOf(s)
	field := st.Field(0)
	fmt.Println(field.Tag.Get("color"), field.Tag.Get("species"))
}
```

The debugger console shows:
```
2016/02/11 23:36:09 debugger.go:58: launching process with args: [./debug]
2016/02/11 23:36:09 debugger.go:191: created breakpoint: &api.Breakpoint{ID:1, Addr:0x4010f9, File:"d:/dev/projects/_go/src/github.com/asampal/hello/hello.go", Line:15, FunctionName:"main.main", Tracepoint:false, Stacktrace:0, Goroutine:false, Variables:[]string(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2016/02/11 23:36:09 debugger.go:260: continuing
panic: runtime error: cgo argument has Go pointer to Go pointer
goroutine 51 [running]:
github.com/derekparker/delve/proc.(*Thread).readMemory(0xc08200e2d0, 0xc08201e000, 0x168, 0x0, 0x0, 0x0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/threads_windows.go:162 +0x1ad
github.com/derekparker/delve/proc.cacheMemory(0x18534f0, 0xc08200e2d0, 0xc08201e000, 0x168, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/mem.go:52 +0x2a7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc0820b2460, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:750 +0xf7c
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc0820b2000, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:725 +0xd15
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc0820b2000)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:711 +0x31
github.com/derekparker/delve/proc.(*Variable).parseG(0xc0820b2000, 0xc0820b2000, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/variables.go:364 +0x77d
github.com/derekparker/delve/proc.(*Thread).GetG(0xc08200e2d0, 0xc08200e2d0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/threads.go:317 +0x70
github.com/derekparker/delve/proc.(*Thread).SetCurrentBreakpoint(0xc08200e2d0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/threads.go:371 +0x195
github.com/derekparker/delve/proc.(*Process).setCurrentBreakpoints(0xc08217e380, 0xc08200e2d0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/proc_windows.go:458 +0x34
github.com/derekparker/delve/proc.(*Process).Continue(0xc08217e380, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/proc/proc.go:393 +0x208
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc0820082a0, 0xc0824a85a0, 0x0, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/service/debugger/debugger.go:261 +0x785
github.com/derekparker/delve/service/rpc.(*RPCServer).Command(0xc082004880, 0xc0824a85a0, 0xc0824ac140, 0x0, 0x0)
	d:/dev/projects/_go/src/github.com/derekparker/delve/service/rpc/server.go:107 +0x46
reflect.Value.call(0xa18740, 0xb174f8, 0x13, 0xb39928, 0x4, 0xc08258fed8, 0x3, 0x3, 0x0, 0x0, ...)
	d:/dev/go/src/reflect/value.go:435 +0x1214
reflect.Value.Call(0xa18740, 0xb174f8, 0x13, 0xc08258fed8, 0x3, 0x3, 0x0, 0x0, 0x0)
	d:/dev/go/src/reflect/value.go:303 +0xb8
net/rpc.(*service).call(0xc0824a60c0, 0xc0824a6080, 0xc082618018, 0xc082180180, 0xc0824a8200, 0x92f960, 0xc0824a85a0, 0x16, 0x92f9c0, 0xc0824ac140, ...)
	d:/dev/go/src/net/rpc/server.go:383 +0x1c9
created by net/rpc.(*Server).ServeCodec
	d:/dev/go/src/net/rpc/server.go:477 +0x4a4
```

**Comment by lukehoban** [comment]
This is related to https://github.com/derekparker/delve/issues/412 and https://github.com/derekparker/delve/issues/363#issuecomment-176024926.

I believe the fix for #412 should address all three of these issues.
