### ISSUE TITLE
proc: cannot launch without absolute path to the binary

### ISSUE THREAD

**Issue by rakyll** [derekparker/delve#576]
Consider the following program where runv is a go program:

```
	p, err := proc.Launch("runv")
	if err != nil {
		panic(err)
	}
```

If fails with the following. Expected behavior is to be able to fork runv which is in my PATH.

```
panic: stat /Users/jbd/src/github.com/rakyll/gtrace/cmd/gtrace/runv: no such file or directory

goroutine 1 [running]:
panic(0x425c980, 0xc8200789f0)
	/Users/jbd/go/src/runtime/panic.go:464 +0x3e6
main.main()
	/Users/jbd/src/github.com/rakyll/gtrace/cmd/gtrace/main.go:29 +0x2a9
```

**Comment by aarzilli** [comment]
`proc.Launch` is an internal interface. I think at this point it should stay the way it is.
