### ISSUE TITLE
delve produce wrong binaries (cgo)

### ISSUE THREAD

**Issue by heretic13** [derekparker/delve#631]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Version: 0.11.0-alpha

2. What version of Go are you using? (`go version`)?
go version go1.7 windows/amd64

3. What operating system and processor architecture are you using?
Windows 10 x64

4. What did you do?
I install MinGW x64.
I download source sqlite-driver - **go get github.com/mattn/go-sqlite3**
I create empty folder and copy file https://github.com/mattn/go-sqlite3/blob/master/_example/simple/simple.go into it.

then i do
**dlv debug** (in current directory)
Then I exit delve. I rename the file **debug** to **debug.exe** and run it.

5. What did you expect to see?
Something meaningful that shows the sqlite tests passed.

6. What did you see instead?
`Exception 0xc0000005 0x8 0x67d328 0x67d328
PC=0x67d328
signal arrived during external code execution

github.com/mattn/go-sqlite3._Cfunc__sqlite3_exec(0x1136b48, 0x342fa90, 0xc042004348, 0xc042004350, 0x0)
        github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:189 +0x54
github.com/mattn/go-sqlite3.(*SQLiteConn).exec(0xc04200a230, 0x5d4c9a, 0x54, 0x0, 0x0, 0x0, 0x0)
        D:/Projects/gopath/src/github.com/mattn/go-sqlite3/sqlite3.go:469 +0x16f
github.com/mattn/go-sqlite3.(*SQLiteConn).Exec(0xc04200a230, 0x5d4c9a, 0x54, 0x6aed68, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc04206e000)
        D:/Projects/gopath/src/github.com/mattn/go-sqlite3/sqlite3.go:406 +0x559
database/sql.(*DB).exec(0xc04206e000, 0x5d4c9a, 0x54, 0x0, 0x0, 0x0, 0xc042035601, 0x0, 0x0, 0x0, ...)
        C:/Go/src/database/sql/sql.go:1036 +0x4d1
database/sql.(*DB).Exec(0xc04206e000, 0x5d4c9a, 0x54, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/database/sql/sql.go:1010 +0xa9
main.main()
        D:/Projects/gopath/src/TestDB/simple.go:25 +0x2bc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc04206e000)
        C:/Go/src/database/sql/sql.go:730 +0x51
created by database/sql.Open
        C:/Go/src/database/sql/sql.go:493 +0x1f0
rax     0x0
rbx     0x3
rcx     0x1d8
rdi     0x1
rsi     0x1137a58
rbp     0x0
rsp     0x9ef7e8
r8      0x1
r9      0x0
r10     0x0
r11     0x246
r12     0x1136b48
r13     0x1
r14     0x40
r15     0x0
rip     0x67d328
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
`

**Comment by aarzilli** [comment]
Delve just calls the normal go compiler, so I think this bug should be reported on the go repository. Running `go build -gcflags='-N -l'` manually on that file should produce the same result.

**Comment by heretic13** [comment]
If I do **go build**, that makes working binary.

**Comment by aarzilli** [comment]
Did you pass `-gcflags='-N -l'`?

**Comment by heretic13** [comment]
This is related to https://github.com/Microsoft/vscode-go/issues/472

aarzilli, I'll check now

**Comment by heretic13** [comment]
d:\Projects\gopath\src\TestDB>go build -gcflags='-N -l'
invalid value "'-N" for flag -gcflags: unterminated ' string
usage: build [-o output] [-i] [build flags] [packages]

**Comment by heretic13** [comment]
d:\Projects\gopath\src\TestDB>go build -gcflags="-N -l"

d:\Projects\gopath\src\TestDB>TestDB.exe
0 こんにちわ世界000
1 こんにちわ世界001
2 こんにちわ世界002
3 こんにちわ世界003
4 こんにちわ世界004
5 こんにちわ世界005
6 こんにちわ世界006
7 こんにちわ世界007
8
...

it's working

**Comment by heretic13** [comment]
delve make binaries from command line (analized delve source code)
**go build -gcflags="-N -l" -ldflags="-linkmode internal"**
that's make broken binary

**Comment by aarzilli** [comment]
Looks like that ldflags option was added to work around this issue: https://github.com/golang/go/issues/10776

**Comment by heretic13** [comment]
aarzilli, any solutions?

**Comment by heretic13** [comment]
If it helps:
**go build -gcflags="-N -l" -o debug**  6.3 Mb size
**go build -gcflags="-N -l" -o debug -ldflags="-linkmode internal"**  3.77 Mb size
I think something was missing inside binary

**Comment by aarzilli** [comment]
Unless either https://github.com/golang/go/issues/13672 or https://github.com/golang/go/issues/10776 get fixed I don't think there is any solution.

**Comment by heretic13** [comment]
ok

**Comment by inputusernamehere** [comment]
I had a similar problem and posted a reproduction over on vscode-go before I found this issue.

https://github.com/Microsoft/vscode-go/issues/524

Would it be possible to allow us to choose our own ldflags?

**Comment by aarzilli** [comment]
See `--build-flags`. Also, you can just use `go build` and then run dlv on the resulting executable.

**Comment by inputusernamehere** [comment]
I would like to run Delve from within VS Code, with the vscode-go plugin, so I can't build normally and then debug the executable I think. Honestly I'm not sure exactly how vscode-go launches Delve, or if I can pass any arguments to Delve from within VS Code.

Like @heretic13 said, this works and builds fine: go build `-gcflags="-N -l" -o debug`
But this doesn't work: `dlv debug --build-flags="-ldflags='-linkmode external'"`
Same with: `dlv debug --build-flags="-ldflags=''"`

Here is the error I get:
`could not launch process: Could not determine version number: could not find symbol value for runtime.buildVersion`

**Comment by aarzilli** [comment]
do `go build -gcflags='-N -l' -o debug` then `dlv exec ./debug`, you should get the same error `could not launch process: Could not determine version number: could not find symbol value for runtime.buildVersion`. The reason is golang/go#13672 and golang/go#10776.
