### ISSUE TITLE
Mac install Error

### ISSUE THREAD

**Issue by lizhong8532** [derekparker/delve#641]
```bash
localhost:~ Lee$ brew install go-delve/delve/delve
==> Installing delve from go-delve/homebrew-delve
==> Downloading https://github.com/derekparker/delve/archive/v0.11.0-alpha.tar.gz
Already downloaded: /Library/Caches/Homebrew/delve-0.11.0.tar.gz
==> dlv-cert is already installed, no need to create it
==> make build BUILD_SHA=v0.11.0
Last 15 lines from /Users/lee/Library/Logs/Homebrew/delve/01.make:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/spf13/cobra (from $GOROOT)
	/private/tmp/delve20160918-3394-131atzj/delve-0.11.0-alpha/src/github.com/spf13/cobra (from $GOPATH)
src/github.com/derekparker/delve/dwarf/reader/reader.go:6:2: cannot find package "golang.org/x/debug/dwarf" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/golang.org/x/debug/dwarf (from $GOROOT)
	/private/tmp/delve20160918-3394-131atzj/delve-0.11.0-alpha/src/golang.org/x/debug/dwarf (from $GOPATH)
src/github.com/derekparker/delve/proc/proc_darwin.go:12:2: cannot find package "golang.org/x/debug/macho" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/golang.org/x/debug/macho (from $GOROOT)
	/private/tmp/delve20160918-3394-131atzj/delve-0.11.0-alpha/src/golang.org/x/debug/macho (from $GOPATH)
src/github.com/derekparker/delve/proc/proc_darwin.go:21:2: cannot find package "golang.org/x/sys/unix" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/golang.org/x/sys/unix (from $GOROOT)
	/private/tmp/delve20160918-3394-131atzj/delve-0.11.0-alpha/src/golang.org/x/sys/unix (from $GOPATH)
src/github.com/derekparker/delve/config/config.go:10:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/gopkg.in/yaml.v2 (from $GOROOT)
	/private/tmp/delve20160918-3394-131atzj/delve-0.11.0-alpha/src/gopkg.in/yaml.v2 (from $GOPATH)
make: *** [build] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/go-delve/homebrew-delve/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:472:in `open'
	from /usr/local/Library/Homebrew/utils.rb:502:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:534:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:218:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:261:in `dump'
	from /usr/local/Library/brew.rb:195:in `rescue in <main>'
	from /usr/local/Library/brew.rb:79:in `<main>'

```
Who can tell me how to fix this issue? Help me please!

**Comment by aarzilli** [comment]
Closing this in favor of https://github.com/go-delve/homebrew-delve/issues/3
