### ISSUE TITLE
32-bit Windows support

### ISSUE THREAD

**Issue by techtonik** [derekparker/delve#656]
A separate issue to track Windows support in #20.
```
C:\go>go get github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/proc
src\github.com\derekparker\delve\proc\disasm.go:9: undefined: ArchInst
```

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? go1.6.3 windows/386
3. What operating system and processor architecture are you using? Vista 32 Intel
4. What did you do? Tried to install delve
5. What did you expect to see? Install successful
6. What did you see instead? See above

**Comment by aicochow** [comment]
I have the same issue

os:windows 7 32 bit
go version: go1.7.1 windows/386

**Comment by swordyang** [comment]
I have the same issue

os:windows 10 64 bit
go version go1.7.3 windows/386

**Comment by CodyGuo** [comment]
set GOARCH=amd64

**Comment by yyf1986** [comment]
my GOARCH=386，when I set GOARCH=amd64，I run ‘go get github.com/derekparker/delve/cmd/dlv’ is ok，but when I debug my code
2017/06/07 10:01:24 server.go:73: Using API v1
2017/06/07 10:01:24 debugger.go:97: launching process with args: [d:\WorkSpace\Go\src\gogo\debug]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xe8 pc=0x640954]
goroutine 1 [running]:
panic(0x943ec0, 0xc04200c080)
C:/go/src/runtime/panic.go:500 +0x1af
github.com/derekparker/delve/vendor/golang.org/x/debug/dwarf.(*Reader).Seek(0xc04231e000, 0xc000000000)
D:/WorkSpace/Go/src/github.com/derekparker/delve/vendor/golang.org/x/debug/dwarf/entry.go:308 +0x364

**Comment by filimonov** [comment]
the same on linux i386

**Comment by Wuaner** [comment]
Cannot believe its still a issue after 8 years.
Any solution?
