### ISSUE TITLE
step panics if source file isn't found in .debug_line

### ISSUE THREAD

**Issue by ignatov** [derekparker/delve#683]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? The latest one from the master.
2. What version of Go are you using? (`go version`)? 1.7.1
3. What operating system and processor architecture are you using?
4. What did you do?

```go
package main

import "fmt"

func main() {
	fmt.Println("adssd") // put a breakpoint here
}
```

and step into until you'll get the exception.

5. What did you expect to see?

6. What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x42caf41]

goroutine 43 [running]:
panic(0x44a8000, 0xc4200140a0)
	/Users/builduser/buildAgent/work/d46533bce70e485f/go/src/runtime/panic.go:500 +0x1a1
github.com/derekparker/delve/dwarf/line.(*DebugLines).AllPCsBetween(0xc42008bed8, 0x7ca90, 0x7ca94, 0x0, 0x0, 0x1, 0x1, 0x0)
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/dwarf/line/state_machine.go:114 +0xb1
github.com/derekparker/delve/proc.(*Process).next(0xc42008be60, 0xc420122601, 0x27290, 0xc42008d1b8)
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/proc/threads.go:236 +0x597
github.com/derekparker/delve/proc.(*Process).Step(0xc42008be60, 0x1, 0x1)
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/proc/proc.go:454 +0xfe
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc4200dd800, 0xc4207d1b48, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/service/debugger/debugger.go:421 +0x515
github.com/derekparker/delve/service/rpc2.(*RPCServer).Command(0xc4201981d0, 0xc4207059b8, 0x4, 0x0, 0x0, 0x4d1faf0, 0xc4201a9540)
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/service/rpc2/server.go:85 +0x51
reflect.Value.call(0xc420244b40, 0xc420132330, 0x13, 0x4527879, 0x4, 0xc420534050, 0x3, 0x3, 0x339, 0x745d9, ...)
	/Users/builduser/buildAgent/work/d46533bce70e485f/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc420244b40, 0xc420132330, 0x13, 0xc420534050, 0x3, 0x3, 0x0, 0x0, 0x370)
	/Users/builduser/buildAgent/work/d46533bce70e485f/go/src/reflect/value.go:302 +0xa4
created by github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/service/rpccommon/server.go:299 +0xa38
```

**Comment by aarzilli** [comment]
original title: `panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by ignatov** [comment]
@aarzilli Any progress?
