### ISSUE TITLE
Crash on `info locals` on OS X

### ISSUE THREAD

**Issue by ansel1** [derekparker/delve#82]
Also on `info locals`.  `info args` doesn't crash, but doesn't show any output, though there is an arg to the function.  And finally, the `p` command always reports `Command failed: could not read memory`.

```
new thread spawned 5891
Type 'help' for list of commands.
(dlv) c
INFO[0003] Request params                                params=[{"Key":"accountid","Value":"85655878-c13d-4a0e-b94b-d5c2c1247b6a"}]
new thread spawned 6919
new thread spawned 7171
thread context changed from 5891 to 7171
current loc: safex/controllers.CreateDomain /Volumes/Pouch/Users/russegan/dev/go/src/safex/controllers/domains.go:18
   13:     domain := models.Domain{}
   14:     if c.Bind(&domain) {
   15:         jsonParams, _ := json.Marshal(c.Params)
   16:         log.WithField("params", string(jsonParams)).Info("Request params")
   17:         runtime.Breakpoint()
=> 18:         if accountId := c.Params.ByName("accountid"); accountId != "" {
   19:             domain.AccountId = accountId
   20:         }
   21:         if err := appContext.Db().Create(&domain).Error; err != nil {
   22:             log.WithFields(log.Fields{"err": err}).Panic("Failed to create domain")
   23:         }

(dlv) info locals
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
github.com/derekparker/delve/proctl.readMemory(0xc2085cf680, 0x0, 0x42ceb48, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/proctl/threads_darwin.go:73 +0xf8
github.com/derekparker/delve/proctl.(*ThreadContext).readMemory(0xc2085cf680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/proctl/variables.go:915 +0xb7
github.com/derekparker/delve/proctl.(*ThreadContext).readString(0xc2085cf680, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/proctl/variables.go:711 +0x1ee
github.com/derekparker/delve/proctl.(*ThreadContext).extractValueInternal(0xc2085cf680, 0x0, 0x0, 0x0, 0xc208031980, 0x41ac680, 0xc20868afc0, 0x1, 0x1, 0x0, ...)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/proctl/variables.go:643 +0x70a
github.com/derekparker/delve/proctl.(*ThreadContext).extractValueInternal(0xc2085cf680, 0x0, 0x0, 0x0, 0xc208031980, 0x41ac680, 0xc20868af60, 0x1, 0x0, 0x0, ...)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/proctl/variables.go:652 +0x9a7
github.com/derekparker/delve/proctl.(*ThreadContext).extractValueInternal(0xc2085cf680, 0xc208239f3f, 0x5, 0x11248a, 0xc20809b600, 0x41a5d00, 0xc20868d4a0, 0x1, 0x0, 0x0, ...)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/proctl/variables.go:634 +0x15ea
github.com/derekparker/delve/proctl.(*ThreadContext).extractValue(0xc2085cf680, 0xc208239f3f, 0x5, 0x11248a, 0x0, 0x41a5d00, 0xc20868d4a0, 0xc2085fb701, 0x0, 0x0, ...)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/proctl/variables.go:597 +0xb8
github.com/derekparker/delve/proctl.(*ThreadContext).extractVariableFromEntry(0xc2085cf680, 0xc20868d440, 0x0, 0x0, 0x0)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/proctl/variables.go:530 +0x55f
github.com/derekparker/delve/proctl.(*ThreadContext).variablesByTag(0xc2085cf680, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/proctl/variables.go:945 +0x238
github.com/derekparker/delve/proctl.(*ThreadContext).LocalVariables(0xc2085cf680, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/proctl/variables.go:366 +0x5d
github.com/derekparker/delve/command.info(0xc208032360, 0xc2085cfa30, 0x1, 0x1, 0x0, 0x0)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/command/command.go:283 +0x9cd
github.com/derekparker/delve/client/cli.Run(0xc20800a010, 0x1, 0x1)
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/client/cli/cli.go:114 +0xa9d
main.main()
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/cmd/dlv/main.go:52 +0x330

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [chan receive]:
github.com/derekparker/delve/client/cli.func·001()
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/client/cli/cli.go:82 +0x65
created by github.com/derekparker/delve/client/cli.Run
        /Volumes/Pouch/Users/russegan/dev/go/src/github.com/derekparker/delve/client/cli/cli.go:87 +0x616

```

**Comment by derekparker** [comment]
Thanks, I was just able to reproduce this locally. Looks like an issue with cgo enabled programs (in your example, include net/http enables cgo).

I'll investigate this.

**Comment by bforsyth927** [comment]
My friend and I hit this issue and debugged through it.  At least for all the cases we hit (both for 'info vars' and 'info locals') the underlying issue was always that it was drilling into an array of strings.  And it would blow up when one of the strings was nil (length == 0, ptr == 0).  The fix or workaround I used in my own copy of Delve is pretty straightforward.  Basically just return the empty string "" out of readString, rather than attempting to dereference a null pointer and construct a string struct at that bogus address.  I'm happy to generate a pull request if you like.  But I'm not (yet) set up to run tests with Delve so it might be a few days before I can get around to it.  What would you like me to do?

diff --git a/proctl/variables.go b/proctl/variables.go
index 4554bc4..f0735bf 100644
--- a/proctl/variables.go
+++ b/proctl/variables.go
@@ -693,6 +693,10 @@ func (thread *ThreadContext) readString(addr uintptr) (string, error) {
        }
        addr = uintptr(binary.LittleEndian.Uint64(val))
 
+       if addr == 0 {
+               return "", err
+       }
+       
        val, err = thread.readMemory(addr, strlen)
        if err != nil {
                return "", err

**Comment by derekparker** [comment]
@bforsyth927 that looks like a pretty reasonable patch. If you submit a PR I'll merge it in.
