### ISSUE TITLE
FAIL: TestDebugLinePrologueParser

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#885]
Running tests @ https://github.com/derekparker/delve/commit/04c4b019f7557344910ade621f68e2695eabe2e5 on Windows 10 with Go 1.9 gives this:

```
--- FAIL: TestDebugLinePrologueParser (0.98s)
panic: Could not parse string [recovered]
        panic: Could not parse string

goroutine 22 [running]:
testing.tRunner.func1(0xc0420a80f0)
        C:/Go1.9/src/testing/testing.go:719 +0x2e3
panic(0x5537e0, 0x5acea0)
        C:/Go1.9/src/runtime/panic.go:491 +0x291
github.com/derekparker/delve/pkg/dwarf/util.ParseString(0xc042190070, 0xc042033cb8, 0x534099, 0x646460)
        D:/go/src/github.com/derekparker/delve/pkg/dwarf/util/util.go:77 +0x8f
github.com/derekparker/delve/pkg/dwarf/line.parseIncludeDirs(0xc0420d3980, 0xc042190070)
        D:/go/src/github.com/derekparker/delve/pkg/dwarf/line/line_parser.go:96 +0x39
github.com/derekparker/delve/pkg/dwarf/line.Parse(0xc042194000, 0x10600, 0x10600, 0xc042194000, 0x10600, 0x10600)
        D:/go/src/github.com/derekparker/delve/pkg/dwarf/line/line_parser.go:61 +0x193
github.com/derekparker/delve/pkg/dwarf/line.TestDebugLinePrologueParser(0xc0420a80f0)
        D:/go/src/github.com/derekparker/delve/pkg/dwarf/line/line_parser_test.go:61 +0x317
testing.tRunner(0xc0420a80f0, 0x59aad8)
        C:/Go1.9/src/testing/testing.go:754 +0xd7
created by testing.(*T).Run
        C:/Go1.9/src/testing/testing.go:800 +0x31b
FAIL    github.com/derekparker/delve/pkg/dwarf/line     1.215s
```

**Comment by dlsniper** [comment]
This also happens with Go 1.8.3

**Comment by dlsniper** [comment]
I've added a bit of debugging for the error message but it's not that helpful:

```
--- FAIL: TestDebugLinePrologueParser (1.08s)
panic: Could not parse string "" from "" [recovered]
        panic: Could not parse string "" from ""

goroutine 35 [running]:
testing.tRunner.func1(0xc042050340)
        c:/go/src/testing/testing.go:622 +0x2a4
panic(0x551300, 0xc04217a2c0)
        c:/go/src/runtime/panic.go:489 +0x2dd
github.com/derekparker/delve/pkg/dwarf/util.ParseString(0xc0421521c0, 0x53278f, 0x62f440, 0xc0421521c0)
        D:/go/src/github.com/derekparker/delve/pkg/dwarf/util/util.go:80 +0x213
github.com/derekparker/delve/pkg/dwarf/line.parseIncludeDirs(0xc0420f8960, 0xc0421521c0)
        D:/go/src/github.com/derekparker/delve/pkg/dwarf/line/line_parser.go:96 +0x36
github.com/derekparker/delve/pkg/dwarf/line.Parse(0xc04217c000, 0xfc00, 0xfc00, 0xc04217c000, 0xfc00, 0xfc00)
        D:/go/src/github.com/derekparker/delve/pkg/dwarf/line/line_parser.go:61 +0x177
github.com/derekparker/delve/pkg/dwarf/line.TestDebugLinePrologueParser(0xc042050340)
        D:/go/src/github.com/derekparker/delve/pkg/dwarf/line/line_parser_test.go:61 +0x358
testing.tRunner(0xc042050340, 0x597348)
        c:/go/src/testing/testing.go:657 +0x9d
created by testing.(*T).Run
        c:/go/src/testing/testing.go:697 +0x2d1
FAIL    github.com/derekparker/delve/pkg/dwarf/line     2.422s
```

It seems that the data source is empty.

**Comment by aarzilli** [comment]
Can you build _fixtures/testnextprog.go with -gcflags='-N -l' and upload it somewhere?

**Comment by dlsniper** [comment]
Please see attached: [issue885.zip](https://github.com/derekparker/delve/files/1092939/issue885.zip)
