### ISSUE TITLE
SIGSEGV in dwarf reader during dlv attach 

### ISSUE THREAD

**Issue by charles-dyfis-net** [derekparker/delve#940]
1. What version of Delve are you using (`dlv version`)?

   ```
   Delve Debugger
   Version: 1.0.0-rc.1
   Build:
   ```

2. What version of Go are you using? (`go version`)?

   ```
   go version go1.8.1 linux/amd64
   ```

3. What operating system and processor architecture are you using?

   Arch Linux, x86_64

4. What did you do?

   ```
   # dlv attach "$pid"
   ```

   The PID is that of an uninstrumented program (compiled without `-gcflags`).

5. What did you expect to see?

   An interactive debugger prompt

6. What did you see instead?

   A stacktrace, given in full at https://gist.github.com/charles-dyfis-net/3edf5d4a8a835f925506bcb38096728e, beginning with the following lines:

   ```
   panic: runtime error: invalid memory address or nil pointer dereference
   [signal SIGSEGV: segmentation violation code=0x1 addr=0xf0 pc=0x628074]

   goroutine 1 [running]:
   github.com/derekparker/delve/vendor/golang.org/x/debug/dwarf.(*Reader).Seek(0xc4201ce090, 0xc400000000)
   	/data/build/builds/delve/src/src/github.com/derekparker/delve/vendor/golang.org/x/debug/dwarf/entry.go:308 +0x354
   github.com/derekparker/delve/vendor/golang.org/x/debug/dwarf.(*Data).Reader(0x0, 0xc42019f6d8)
   	/data/build/builds/delve/src/src/github.com/derekparker/delve/vendor/golang.org/x/debug/dwarf/entry.go:291 +0x5f
   github.com/derekparker/delve/pkg/dwarf/reader.New(0x0, 0x9e1018)
   	/data/build/builds/delve/src/src/github.com/derekparker/delve/pkg/dwarf/reader/reader.go:18 +0x2f
   ```

**Comment by aarzilli** [comment]
Can you run `objdump -h path_to_your_executable` and post the output?

**Comment by charles-dyfis-net** [comment]
```
/usr/bin/REDACTED:     file format elf64-x86-64

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .text         002dceee  0000000000400c00  0000000000400c00  00000c00  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .plt          00000140  00000000006ddb00  00000000006ddb00  002ddb00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  2 .rodata       00216b70  00000000006de000  00000000006de000  002de000  2**5
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .typelink     000017f0  00000000008f4b70  00000000008f4b70  004f4b70  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .gosymtab     00000000  00000000008f6360  00000000008f6360  004f6360  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 .gopclntab    001021c2  00000000008f6360  00000000008f6360  004f6360  2**5
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .dynsym       00000258  00000000009f8b80  00000000009f8b80  005f8b80  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  7 .rela         00000018  00000000009f8530  00000000009f8530  005f8530  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  8 .gnu.version  00000032  00000000009f8560  00000000009f8560  005f8560  2**1
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  9 .gnu.version_r 00000040  00000000009f85a0  00000000009f85a0  005f85a0  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 10 .hash         00000084  00000000009f85e0  00000000009f85e0  005f85e0  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 11 .dynstr       0000016b  00000000009f8680  00000000009f8680  005f8680  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 12 .rela.plt     000001c8  00000000009f89a0  00000000009f89a0  005f89a0  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 13 .got          00000008  00000000009f9000  00000000009f9000  005f9000  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 14 .got.plt      000000b0  00000000009f9020  00000000009f9020  005f9020  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 15 .dynamic      00000130  00000000009f90e0  00000000009f90e0  005f90e0  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 16 .noptrdata    000160ec  00000000009f9220  00000000009f9220  005f9220  2**5
                  CONTENTS, ALLOC, LOAD, DATA
 17 .data         0000a570  0000000000a0f320  0000000000a0f320  0060f320  2**5
                  CONTENTS, ALLOC, LOAD, DATA
 18 .bss          00009700  0000000000a198a0  0000000000a198a0  00619890  2**5
                  ALLOC
 19 .noptrbss     00013848  0000000000a22fa0  0000000000a22fa0  00619890  2**5
                  ALLOC
 20 .interp       0000001c  0000000000400be4  0000000000400be4  00000be4  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 21 .tbss         00000010  0000000000000000  0000000000000000  00619890  2**3
                  ALLOC, THREAD_LOCAL
```

**Comment by aarzilli** [comment]
Thank you. The problem is that there are no debug sections in your executable, it was stripped, either with strip or by passing -s to the go linker. We should give a better error message in this case, I'll fix that, but that's all we can do.
